"use client";

import { getFoundation } from "@/application/foundation-service";
import type { Client, Lead, PipelineHistory, PipelineStage } from "@/domains/core/entities";
import { PIPELINE_STAGES } from "@/domains/core/entities";
import { timestamps } from "@/domains/shared/entity";
import { getRepositoryProvider } from "@/repositories/providers";

export const STAGE_LABEL: Record<PipelineStage, string> = { new: "Novo lead", form: "Formulário em preenchimento", calculation: "A calcular", in_progress: "Em andamento", ready: "Pronto para apresentação", presented: "Apresentado", waiting: "Aguardando cliente", closed: "Fechado", lost: "Não fechado" };
const provider = () => getRepositoryProvider();
const daysAgo = (days: number) => new Date(Date.now() - days * 86400000).toISOString();
const future = (days: number) => new Date(Date.now() + days * 86400000).toISOString();

async function tenantId() { const foundation = await getFoundation(); if (!foundation.tenant) throw new Error("A corretora ainda não foi configurada."); return foundation.tenant.id; }
async function history(input: Omit<PipelineHistory, "id" | "createdAt" | "updatedAt" | "version" | "deletedAt" | "tenantId" | "changedAt"> & { tenantId: string; changedAt?: string }) { const event = { ...timestamps(), tenantId: input.tenantId, leadId: input.leadId, clientId: input.clientId, fromStage: input.fromStage, toStage: input.toStage, reason: input.reason, eventType: input.eventType ?? "moved", changedAt: input.changedAt ?? new Date().toISOString() }; await provider().pipelineHistory.create(event); }

export async function ensureCrmDemoData() {
  const id = await tenantId(); const p = provider(); const leads = await p.leads.list(id); const clients = await p.clients.list(id);
  if (leads.length + clients.length >= 13) return;
  const leadRows: Array<Pick<Lead, "name" | "email" | "phone" | "origin" | "profession" | "city" | "nextAction" | "nextActionAt" | "stage" | "potentialValue" | "priority">> = [
    { name: "Carolina Ferreira", email: "carolina@exemplo.com", phone: "(21) 98888-0101", origin: "Indicação", profession: "Médica", city: "Niterói", nextAction: "Primeiro contato", nextActionAt: future(1), stage: "new", potentialValue: 850, priority: "high" },
    { name: "João Cardoso", email: "joao@exemplo.com", phone: "(21) 98888-0102", origin: "Instagram", profession: "Arquiteto", city: "Rio de Janeiro", nextAction: "Enviar formulário", nextActionAt: future(2), stage: "form", potentialValue: 620, priority: "normal" },
    { name: "Marina Azevedo", email: "marina@email.com", phone: "(21) 98888-0000", origin: "Site", profession: "Advogada", city: "Niterói", nextAction: "Revisar proteção familiar", nextActionAt: future(1), stage: "calculation", potentialValue: 980, priority: "high" },
    { name: "Felipe Duarte", email: "felipe@exemplo.com", phone: "(21) 98888-0104", origin: "Evento", profession: "Empresário", city: "São Gonçalo", nextAction: "Retomar proposta", nextActionAt: daysAgo(5), stage: "in_progress", potentialValue: 1100, priority: "high" },
    { name: "Priscila Nunes", email: "priscila@exemplo.com", phone: "(21) 98888-0105", origin: "Indicação", profession: "Professora", city: "Niterói", nextAction: "Agendar apresentação", nextActionAt: future(3), stage: "ready", potentialValue: 540, priority: "normal" },
    { name: "André Lima", email: "andre@exemplo.com", phone: "(21) 98888-0106", origin: "Parceria", profession: "Engenheiro", city: "Rio de Janeiro", nextAction: "Enviar resumo", nextActionAt: future(2), stage: "presented", potentialValue: 760, priority: "normal" },
    { name: "Tatiana Rocha", email: "tatiana@exemplo.com", phone: "(21) 98888-0107", origin: "Site", profession: "Dentista", city: "Niterói", nextAction: "Aguardar retorno", nextActionAt: daysAgo(3), stage: "waiting", potentialValue: 690, priority: "low" },
    { name: "Eduardo Martins", email: "eduardo@exemplo.com", phone: "(21) 98888-0108", origin: "Indicação", profession: "Administrador", city: "Rio de Janeiro", nextAction: "Formalizar contratação", nextActionAt: future(1), stage: "closed", potentialValue: 900, priority: "high" },
  ];
  for (const row of leadRows) { if (leads.some((lead) => lead.email === row.email)) continue; const item: Lead = { ...timestamps(), tenantId: id, ...row, tags: row.origin ? [row.origin] : [], archivedAt: null }; await p.leads.create(item); await history({ tenantId: id, leadId: item.id, toStage: item.stage, eventType: "created", changedAt: daysAgo(item.stage === "waiting" ? 9 : 2) }); }
  const clientRows = ["Rafael Mendes", "Beatriz Sampaio", "Lucas Faria", "Renata Costa", "Paulo Teixeira"];
  for (const [index, name] of clientRows.entries()) { if (clients.some((client) => client.name === name)) continue; const stage: PipelineStage = index === 0 ? "closed" : index === 1 ? "waiting" : index === 2 ? "presented" : index === 3 ? "in_progress" : "lost"; const item: Client = { ...timestamps(), tenantId: id, name, email: `${name.toLowerCase().replaceAll(" ", ".")}@exemplo.com`, phone: `(21) 97777-0${index}00`, profession: ["Consultor", "Fisioterapeuta", "Designer", "Nutricionista", "Contador"][index], company: "Empresa exemplo", status: stage === "lost" ? "inactive" : "active", pipelineStage: stage, nextAction: stage === "closed" ? "Revisão anual" : "Retorno comercial", nextActionAt: future(index + 2), potentialValue: 700 + index * 90 }; await p.clients.create(item); await history({ tenantId: id, clientId: item.id, toStage: stage, eventType: "created", changedAt: daysAgo(index + 1) }); }
}

export async function listLeads(query = "", stage?: PipelineStage, includeArchived = false) { const id = await tenantId(); const normalized = query.trim().toLowerCase(); return (await provider().leads.list(id)).filter((lead) => (includeArchived || !lead.archivedAt) && (!stage || lead.stage === stage) && (!normalized || [lead.name, lead.email, lead.phone, lead.origin].some((value) => value?.toLowerCase().includes(normalized)))).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); }
export async function listClients(query = "") { const id = await tenantId(); const normalized = query.trim().toLowerCase(); return (await provider().clients.list(id)).filter((client) => !normalized || [client.name, client.email, client.phone, client.profession].some((value) => value?.toLowerCase().includes(normalized))).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); }
export async function createLead(input: Pick<Lead, "name" | "email" | "phone" | "origin" | "profession" | "city" | "notes" | "nextAction" | "nextActionAt" | "tags" | "potentialValue">) { const id = await tenantId(); const lead: Lead = { ...timestamps(), tenantId: id, ...input, stage: "new", priority: "normal", archivedAt: null }; await provider().leads.create(lead); await history({ tenantId: id, leadId: lead.id, toStage: lead.stage, eventType: "created" }); return lead; }
export async function updateLead(lead: Lead) { return provider().leads.update(lead); }
export async function archiveLead(lead: Lead) { return provider().leads.update({ ...lead, archivedAt: new Date().toISOString() }); }
export async function convertLead(lead: Lead) { const id = await tenantId(); const existing = (await listClients()).find((client) => (lead.email && client.email === lead.email) || (lead.phone && client.phone === lead.phone)); const client: Client = existing ?? { ...timestamps(), tenantId: id, name: lead.name, sourceLeadId: lead.id, email: lead.email, phone: lead.phone, profession: lead.profession, address: lead.city, notes: lead.notes, status: "active", pipelineStage: lead.stage, nextAction: lead.nextAction, nextActionAt: lead.nextActionAt, potentialValue: lead.potentialValue }; if (!existing) await provider().clients.create(client); await history({ tenantId: id, leadId: lead.id, clientId: client.id, fromStage: lead.stage, toStage: lead.stage, eventType: "converted", reason: existing ? "Possível duplicidade aproveitada" : "Lead convertido em cliente" }); return { client, duplicate: Boolean(existing) }; }
export type PipelineCard = { id: string; kind: "lead" | "client"; name: string; stage: PipelineStage; createdAt: string; updatedAt: string; nextAction?: string; nextActionAt?: string; potentialValue?: number; priority?: string };
export async function listPipeline() { const [leads, clients] = await Promise.all([listLeads(), listClients()]); return [...leads.map((lead): PipelineCard => ({ id: lead.id, kind: "lead", name: lead.name, stage: lead.stage, createdAt: lead.createdAt, updatedAt: lead.updatedAt, nextAction: lead.nextAction, nextActionAt: lead.nextActionAt, potentialValue: lead.potentialValue, priority: lead.priority })), ...clients.filter((client) => client.pipelineStage).map((client): PipelineCard => ({ id: client.id, kind: "client", name: client.name, stage: client.pipelineStage!, createdAt: client.createdAt, updatedAt: client.updatedAt, nextAction: client.nextAction, nextActionAt: client.nextActionAt, potentialValue: client.potentialValue }))]; }
export async function movePipelineCard(card: PipelineCard, toStage: PipelineStage, reason?: string) { if (card.stage === toStage) return; const p = provider(); const changedAt = new Date().toISOString(); if (card.kind === "lead") { const lead = await p.leads.findById(card.id); if (!lead) throw new Error("Lead não encontrado."); await p.leads.update({ ...lead, stage: toStage }); } else { const client = await p.clients.findById(card.id); if (!client) throw new Error("Cliente não encontrado."); await p.clients.update({ ...client, pipelineStage: toStage }); } const id = await tenantId(); await history({ tenantId: id, leadId: card.kind === "lead" ? card.id : undefined, clientId: card.kind === "client" ? card.id : undefined, fromStage: card.stage, toStage, reason, eventType: "moved", changedAt }); }
export async function prepareDiagnosticCompletedCard(clientId: string) { const client = await provider().clients.findById(clientId); if (!client) throw new Error("Cliente não encontrado."); await movePipelineCard({ id: client.id, kind: "client", name: client.name, stage: client.pipelineStage ?? "form", createdAt: client.createdAt, updatedAt: client.updatedAt }, "calculation", "Diagnóstico concluído"); return provider().tasks.create({ ...timestamps(), tenantId: client.tenantId, title: `Calcular proteção de ${client.name}`, status: "open", relatedId: client.id }); }
export async function dashboardMetrics() { const [cards, histories] = await Promise.all([listPipeline(), (async () => { const id = await tenantId(); return provider().pipelineHistory.list(id); })()]); const counts = Object.fromEntries(PIPELINE_STAGES.map((stage) => [stage, cards.filter((card) => card.stage === stage).length])) as Record<PipelineStage, number>; const stale = cards.filter((card) => Date.now() - new Date(card.updatedAt).getTime() > 7 * 86400000).length; const closed = counts.closed; const started = cards.length - counts.lost; return { cards, counts, stale, conversion: started ? Math.round((closed / started) * 100) : 0, newLeads: cards.filter((card) => card.kind === "lead" && Date.now() - new Date(card.updatedAt).getTime() < 30 * 86400000).length, histories } }
