import type { MetisAnalysisType, MetisStructuredResult, MetisUsage } from "@/domains/core/entities";
import type { SanitizedMetisContext } from "@/application/metis-sanitizer";
import { validateMetisResult } from "@/application/metis-schema";
import { demoSessionId, isDemoMode } from "@/lib/demo-mode";

export type MetisProviderResponse = { result: MetisStructuredResult; model: string; durationMs?: number; usage?: MetisUsage };
export class MetisProviderError extends Error { constructor(message: string, readonly code: string, readonly retryable = false) { super(message); } }
export interface MetisAiProvider { name: string; model: string; analyze(context: SanitizedMetisContext): Promise<MetisProviderResponse>; }

const disclaimer = "Conteúdo de apoio produzido por IA. Revise os fatos, as inferências e a adequação da proposta antes de qualquer orientação ao cliente. A Metis não garante aceitação de seguro nem substitui a decisão profissional da corretora.";
const missing = (context: SanitizedMetisContext) => [!context.diagnosis.income && "Renda familiar não informada.", !context.diagnosis.expenses && "Despesas mensais não informadas.", !context.diagnosis.goals && "Objetivos e prioridades não informados.", !context.diagnosis.existingInsurance && "Seguros existentes não informados."].filter(Boolean) as string[];

export const fakeMetisProvider: MetisAiProvider = { name: "fake", model: "metis-demo-1", async analyze(context) { if (process.env.NEXT_PUBLIC_METIS_SIMULATE_FAILURE === "true") throw new MetisProviderError("Falha simulada da Metis. Nenhum dado foi alterado.", "simulated_failure", true); const incomplete = missing(context); const base: MetisStructuredResult = { summary: context.diagnosis.family ? `Perfil familiar registrado: ${context.diagnosis.family}` : "Perfil financeiro em consolidação.", attentionPoints: [context.diagnosis.debts ? "Há dívidas ou compromissos a considerar na continuidade da renda." : "Confirme compromissos financeiros antes de definir prioridades.", context.diagnosis.existingInsurance ? "Compare as proteções existentes com os objetivos declarados." : "Mapeie as proteções existentes antes de concluir a análise."], protectionTopics: ["Continuidade de renda e manutenção do padrão de vida.", "Coberturas compatíveis com os objetivos declarados, sujeitas à análise da corretora."], questions: ["Qual compromisso financeiro teria maior impacto para a família em uma ausência de renda?", "Quais objetivos familiares precisam de proteção prioritária nesta fase?"], missingInformation: incomplete, disclaimer }; if (context.analysisType === "meeting_questions") base.questions = [...base.questions, "Houve mudança recente em renda, despesas, patrimônio ou dependentes?"]; if (context.analysisType === "proposal_review") base.proposalReview = { alignedItems: context.proposal?.coverages.map((coverage) => `${coverage.label}: finalidade registrada para revisão.`) ?? [], reviewItems: ["Confirme se o capital segurado atende aos objetivos sem tratá-lo como rendimento.", ...(incomplete.length ? ["Existem informações incompletas que limitam a aderência da proposta."] : [])] }; return { result: base, model: "metis-demo-1", durationMs: 0 }; } };
export const failingMetisProvider: MetisAiProvider = { name: "fake", model: "metis-demo-1", async analyze() { throw new MetisProviderError("Falha simulada da Metis. Nenhum dado foi alterado.", "simulated_failure", true); } };
export const openAiMetisProvider: MetisAiProvider = { name: "openai", model: "gpt-4.1-mini", async analyze(context) { let response: Response; try { const session = isDemoMode() ? demoSessionId() : null; response = await fetch("/api/metis", { method: "POST", headers: { "content-type": "application/json", ...(session ? { "x-7protect-demo-session": session } : {}) }, body: JSON.stringify({ context }) }); } catch { throw new MetisProviderError("Não foi possível alcançar o serviço da Metis. Tente novamente.", "network_error", true); } const body = await response.json().catch(() => ({})) as { result?: unknown; error?: string; code?: string; retryable?: boolean; model?: string; durationMs?: number; usage?: MetisUsage }; if (!response.ok) throw new MetisProviderError(body.error ?? "A Metis não pôde concluir a análise.", body.code ?? "provider_error", Boolean(body.retryable)); const result = validateMetisResult(body.result); const model = body.model ?? this.model; this.model = model; return { result, model, durationMs: body.durationMs, usage: body.usage }; } };
export function selectMetisProvider(): MetisAiProvider { return process.env.NEXT_PUBLIC_METIS_PROVIDER === "openai" ? openAiMetisProvider : fakeMetisProvider; }
export const analysisLabel: Record<MetisAnalysisType, string> = { diagnostic: "Análise do diagnóstico", proposal_review: "Revisão da proposta", meeting_questions: "Perguntas para reunião" };
