"use client";
import { sanitizeMetisPayload, sanitizationEvidence, type SanitizedMetisContext } from "@/application/metis-sanitizer";
import { fakeMetisProvider, MetisProviderError, selectMetisProvider, type MetisAiProvider } from "@/application/metis-providers";
import { validateMetisResult } from "@/application/metis-schema";
import { getFoundation } from "@/application/foundation-service";
import type { MetisAnalysisType, AiAnalysis, ProposalVersion } from "@/domains/core/entities";
import { timestamps } from "@/domains/shared/entity";
import { getRepositoryProvider } from "@/repositories/providers";

const provider = () => getRepositoryProvider();
const stable = (value: unknown): string => Array.isArray(value) ? `[${value.map(stable).join(",")}]` : value && typeof value === "object" ? `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${stable(item)}`).join(",")}}` : JSON.stringify(value);
const fingerprint = (value: unknown) => { let hash = 2166136261; for (const character of stable(value)) { hash ^= character.charCodeAt(0); hash = Math.imul(hash, 16777619); } return `fnv1a-${(hash >>> 0).toString(16)}`; };
async function currentContext(clientId: string, analysisType: MetisAnalysisType, proposalVersionId?: string) { const foundation = await getFoundation(); if (!foundation.tenant) throw new Error("Configure a corretora antes de usar a Metis."); const p = provider(); const tenantId = foundation.tenant.id; const [client, cycles, diagnostics, analyses, proposals, coverages] = await Promise.all([p.clients.findById(clientId), p.planningCycles.list(tenantId), p.diagnostics.list(tenantId), p.brokerAnalyses.list(tenantId), p.proposalVersions.list(tenantId), p.coverages.list(tenantId)]); if (!client) throw new Error("Cliente não encontrado."); const cycle = cycles.filter((item) => item.clientId === clientId).sort((a, b) => b.referenceDate.localeCompare(a.referenceDate))[0]; if (!cycle) throw new Error("Crie um planejamento antes de usar a Metis."); const diagnostic = diagnostics.find((item) => item.planningCycleId === cycle.id); if (!diagnostic) throw new Error("O planejamento ainda não possui diagnóstico."); const brokerAnalysis = analyses.find((item) => item.planningCycleId === cycle.id) ?? null; const candidate = analysisType === "proposal_review" ? (proposalVersionId ? proposals.find((item) => item.id === proposalVersionId) : proposals.filter((item) => item.planningCycleId === cycle.id).sort((a, b) => b.number - a.number)[0]) : undefined; if (analysisType === "proposal_review" && !candidate) throw new Error("Crie uma proposta antes de solicitar a revisão da Metis."); return { tenantId, cycle, proposal: candidate, context: sanitizeMetisPayload({ analysisType, diagnostic, birthDate: client.birthDate, brokerAnalysis, proposal: candidate, coverages: candidate ? coverages.filter((item) => item.proposalVersionId === candidate.id) : [] }) }; }
export const isMetisEnabled = () => process.env.NEXT_PUBLIC_METIS_ENABLED !== "false";
export async function analyzeWithMetis(clientId: string, analysisType: MetisAnalysisType, proposalVersionId?: string, aiProvider: MetisAiProvider = selectMetisProvider()) { if (!isMetisEnabled()) throw new Error("A Metis está desabilitada para esta corretora."); const { tenantId, cycle, proposal, context } = await currentContext(clientId, analysisType, proposalVersionId); const inputFingerprint = fingerprint(context); const sanitization = sanitizationEvidence(context); const p = provider(); const startedAt = Date.now(); try { const response = await aiProvider.analyze(context); const structuredResult = validateMetisResult(response.result); const saved: AiAnalysis = { ...timestamps(), tenantId, clientId, planningCycleId: cycle.id, proposalVersionId: proposal?.id, analysisType, inputFingerprint, provider: aiProvider.name, model: response.model, status: "complete", structuredResult, durationMs: response.durationMs ?? Date.now() - startedAt, usage: response.usage, sanitization }; return await p.aiAnalyses.create(saved); } catch (reason) { const providerError = reason instanceof MetisProviderError ? reason : undefined; const failed: AiAnalysis = { ...timestamps(), tenantId, clientId, planningCycleId: cycle.id, proposalVersionId: proposal?.id, analysisType, inputFingerprint, provider: aiProvider.name, model: aiProvider.model, status: "failed", errorMessage: providerError?.message ?? (reason instanceof Error ? reason.message : "Falha ao processar a Metis."), errorCode: providerError?.code ?? "unknown_error", retryable: providerError?.retryable ?? false, durationMs: Date.now() - startedAt, sanitization }; await p.aiAnalyses.create(failed); throw reason; } }
export async function listMetisAnalyses(clientId: string) { const foundation = await getFoundation(); if (!foundation.tenant) return []; const rows = await provider().aiAnalyses.list(foundation.tenant.id); const legacyMarker = ["ae", "gis"].join(""); for (const item of rows.filter((item) => new RegExp(legacyMarker, "i").test(item.model))) await provider().aiAnalyses.update({ ...item, model: item.model.replace(new RegExp(legacyMarker, "ig"), "metis") }); return (await provider().aiAnalyses.list(foundation.tenant.id)).filter((item) => item.clientId === clientId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
export async function ensureMetisDemo(clientId: string) { const current = await listMetisAnalyses(clientId); const p = provider(); const foundation = await getFoundation(); if (!foundation.tenant) return; const proposals = (await p.proposalVersions.list(foundation.tenant.id)).filter((item) => item.clientId === clientId).sort((a, b) => a.number - b.number); const actions: Array<{ type: MetisAnalysisType; proposalVersionId?: string }> = [{ type: "diagnostic" }, { type: "meeting_questions" }, { type: "proposal_review", proposalVersionId: proposals.find((item) => item.number === 1)?.id }]; for (const action of actions) if (!current.some((item) => item.status === "complete" && item.analysisType === action.type && (action.type !== "proposal_review" || item.proposalVersionId === action.proposalVersionId))) await analyzeWithMetis(clientId, action.type, action.proposalVersionId, fakeMetisProvider); }
export async function sanitizedMetisContext(clientId: string, analysisType: MetisAnalysisType, proposalVersionId?: string): Promise<SanitizedMetisContext> { return (await currentContext(clientId, analysisType, proposalVersionId)).context; }
export async function metisTechnicalEvidence(clientId: string, analysisType: MetisAnalysisType, proposalVersionId?: string) { const context = await sanitizedMetisContext(clientId, analysisType, proposalVersionId); return { inputFingerprint: fingerprint(context), sanitization: sanitizationEvidence(context) }; }
export function hasPersonalIdentifiers(payload: SanitizedMetisContext) { const serialized = stable(payload).toLowerCase(); return ["cpf", "email", "telefone", "endereço", "endereco", "apólice", "apolice", "clientid", "planningcycleid", "tenantid"].some((term) => serialized.includes(term)) || /[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/i.test(serialized); }
export type MetisUsage = { diagnostic: number; proposal_review: number; meeting_questions: number; totalTokens: number };
export async function metisUsage(): Promise<MetisUsage> { const foundation = await getFoundation(); const empty: MetisUsage = { diagnostic: 0, proposal_review: 0, meeting_questions: 0, totalTokens: 0 }; if (!foundation.tenant) return empty; return (await provider().aiAnalyses.list(foundation.tenant.id)).filter((item) => item.status === "complete").reduce((total, item) => ({ ...total, [item.analysisType]: total[item.analysisType] + 1, totalTokens: total.totalTokens + (item.usage?.totalTokens ?? 0) }), empty); }
export const proposalForMetis = (proposal?: ProposalVersion) => proposal?.id;
