"use client";
import { calculatePlanning } from "@/application/planning-calculations";
import { prepareDiagnosticCompletedCard, movePipelineCard, type PipelineCard } from "@/application/crm-service";
import type { BrokerAnalysis, Client, ClosingRecord, Coverage, Diagnostic, PlanningCycle, PlanningType, ProposalVersion } from "@/domains/core/entities";
import { timestamps } from "@/domains/shared/entity";
import { getFoundation } from "@/application/foundation-service";
import { getRepositoryProvider } from "@/repositories/providers";

const provider = () => getRepositoryProvider();
async function tenantId() { const foundation = await getFoundation(); if (!foundation.tenant) throw new Error("A corretora ainda não foi configurada."); return foundation.tenant.id; }
const number = (value: unknown) => Number(value) || 0;
const draftData = { identification: "", family: "", workIncome: "", expenses: "", assets: "", reserves: "", pensions: "", debts: "", existingInsurance: "", health: "", goals: "", review: "", familyIncome: 0, monthlyExpense: 0 };

export type CreatePlanningInput = { clientId: string; name: string; referenceDate: string; type: PlanningType; observation?: string };
export async function listPlanningClients() { return provider().clients.list(await tenantId()); }
export async function listPlanningCycles(clientId: string) { const id = await tenantId(); return (await provider().planningCycles.list(id)).filter((planning) => planning.clientId === clientId).sort((a, b) => b.startedAt.localeCompare(a.startedAt)); }
export async function createPlanningCycle(input: CreatePlanningInput) {
  const id = await tenantId(); const name = input.name.trim();
  if (!name) throw new Error("Informe o nome do planejamento.");
  if (!input.referenceDate) throw new Error("Informe a data de referência.");
  const planning: PlanningCycle = { ...timestamps(), tenantId: id, clientId: input.clientId, name, type: input.type, referenceDate: input.referenceDate, observation: input.observation?.trim() || undefined, status: "active", startedAt: new Date().toISOString() };
  await provider().planningCycles.create(planning);
  await provider().diagnostics.create({ ...timestamps(), tenantId: id, clientId: input.clientId, planningCycleId: planning.id, planningCycle: planning.name, status: "draft", declaredData: draftData });
  return planning;
}
export async function planningWorkspace(clientId: string, planningId?: string) {
  const cycles = await listPlanningCycles(clientId); const cycle = cycles.find((item) => item.id === planningId) ?? cycles[0] ?? null;
  const id = await tenantId(); const p = provider();
  const [diagnostics, analyses, proposals, closings, insurers, products, coverageTypes] = await Promise.all([p.diagnostics.list(id), p.brokerAnalyses.list(id), p.proposalVersions.list(id), p.closings.list(id), p.insurers.list(id), p.insuranceProducts.list(id), p.coverageTypes.list(id)]);
  if (!cycle) return { cycle: null, cycles, diagnostic: null, analysis: null, proposals: [], closing: null, catalog: { insurers, products, coverageTypes } };
  const diagnostic = diagnostics.find((item) => item.planningCycleId === cycle.id) ?? await p.diagnostics.create({ ...timestamps(), tenantId: id, clientId, planningCycleId: cycle.id, planningCycle: cycle.name, status: "draft", declaredData: draftData });
  const cycleProposals = proposals.filter((item) => item.planningCycleId === cycle.id).sort((a, b) => a.number - b.number);
  const allCoverages = await p.coverages.list(id);
  return { cycle, cycles, diagnostic, analysis: analyses.find((item) => item.planningCycleId === cycle.id) ?? null, proposals: cycleProposals.map((proposal) => ({ proposal, coverages: allCoverages.filter((coverage) => coverage.proposalVersionId === proposal.id) })), closing: closings.find((item) => item.planningCycleId === cycle.id) ?? null, catalog: { insurers, products, coverageTypes } };
}
export async function saveDiagnostic(diagnostic: Diagnostic, declaredData: Record<string, unknown>) { if (diagnostic.status === "completed") throw new Error("Reabra o diagnóstico para editar os dados declarados."); return provider().diagnostics.update({ ...diagnostic, declaredData }); }
export async function completeDiagnostic(diagnostic: Diagnostic) { const updated = await provider().diagnostics.update({ ...diagnostic, status: "completed", completedAt: new Date().toISOString() }); await prepareDiagnosticCompletedCard(diagnostic.clientId); return updated; }
export async function reopenDiagnostic(diagnostic: Diagnostic) { return provider().diagnostics.update({ ...diagnostic, status: "reopened", completedAt: undefined }); }
export async function saveBrokerAnalysis(input: Omit<BrokerAnalysis, "id" | "tenantId" | "createdAt" | "updatedAt" | "version" | "deletedAt"> & { id?: string }) { const p = provider(); if (input.id) { const current = await p.brokerAnalyses.findById(input.id); if (current) return p.brokerAnalyses.update({ ...current, ...input }); } const id = await tenantId(); return p.brokerAnalyses.create({ ...timestamps(), tenantId: id, clientId: input.clientId, planningCycleId: input.planningCycleId, summary: input.summary, priorities: input.priorities, hypotheses: input.hypotheses, estimatedNeed: input.estimatedNeed, timeframe: input.timeframe, calculationNotes: input.calculationNotes, recommendations: input.recommendations, pendingQuestions: input.pendingQuestions, internalNotes: input.internalNotes }); }
export async function seedCatalog() { const id = await tenantId(); const p = provider(); const insurers = await p.insurers.list(id); if (!insurers.length) for (const name of ["MetLife", "Horizonte Seguros"]) await p.insurers.create({ ...timestamps(), tenantId: id, name, active: true }); const currentInsurers = await p.insurers.list(id); if (!(await p.coverageTypes.list(id)).length) for (const name of ["Vida", "Invalidez", "Doenças graves", "Educação", "Sucessão"]) await p.coverageTypes.create({ ...timestamps(), tenantId: id, name, active: true }); if (!(await p.insuranceProducts.list(id)).length) for (const insurer of currentInsurers) await p.insuranceProducts.create({ ...timestamps(), tenantId: id, insurerId: insurer.id, name: `Proteção ${insurer.name}`, category: "Seguro de vida", active: true }); }
export async function addCatalogItem(kind: "insurer" | "product" | "coverageType", name: string, insurerId?: string) { const id = await tenantId(); const p = provider(); if (!name.trim()) throw new Error("Informe um nome para o item do catálogo."); if (kind === "insurer") return p.insurers.create({ ...timestamps(), tenantId: id, name: name.trim(), active: true }); if (kind === "coverageType") return p.coverageTypes.create({ ...timestamps(), tenantId: id, name: name.trim(), active: true }); if (!insurerId) throw new Error("Selecione a seguradora do produto."); return p.insuranceProducts.create({ ...timestamps(), tenantId: id, insurerId, name: name.trim(), active: true }); }
export async function createProposalVersion(cycle: PlanningCycle, diagnostic: Diagnostic, analysis: BrokerAnalysis | null, reason = "Nova versão") { const id = await tenantId(); await seedCatalog(); const p = provider(); const existing = (await p.proposalVersions.list(id)).filter((item) => item.planningCycleId === cycle.id); const previous = existing[existing.length - 1]; if (previous?.status === "draft") await p.proposalVersions.update({ ...previous, status: "superseded" }); const [insurer] = await p.insurers.list(id); const [product] = await p.insuranceProducts.list(id); const need = analysis?.estimatedNeed ?? number(diagnostic.declaredData.estimatedNeed) ?? 0; const monthly = Math.max(120, Math.round(need * 0.00022)); const totals = calculatePlanning({ familyIncome: number(diagnostic.declaredData.familyIncome), monthlyExpense: number(diagnostic.declaredData.monthlyExpense), monthlyPremium: monthly, protectedCapital: need, estimatedNeed: need }); const version: ProposalVersion = { ...timestamps(), tenantId: id, clientId: cycle.clientId, planningCycleId: cycle.id, number: existing.length + 1, status: "draft", revisionReason: reason, generalNote: analysis?.recommendations, totalMonthly: monthly, totalAnnual: totals.annualPremium, totalProtectedCapital: totals.protectedCapital, incomeCommitment: totals.incomeCommitment }; await p.proposalVersions.create(version); await p.coverages.create({ ...timestamps(), tenantId: id, proposalVersionId: version.id, insurerId: insurer?.id, productId: product?.id, coverageType: "Vida", label: "Proteção de vida", objective: "Manutenção do padrão de vida", insuredCapital: need, term: "12 meses renováveis", monthlyPremium: monthly, description: "Cobertura demonstrativa configurada pela corretora.", brokerNote: analysis?.calculationNotes, displayOrder: 1, name: "Proteção de vida" }); return version; }
export async function presentProposal(proposal: ProposalVersion) { if (proposal.status === "presented" || proposal.status === "accepted") return proposal; return provider().proposalVersions.update({ ...proposal, status: "presented", presentedAt: new Date().toISOString() }); }
export async function closePlanning(cycle: PlanningCycle, proposal: ProposalVersion, suggestedReviewAt?: string) { if (proposal.status !== "presented" && proposal.status !== "accepted") throw new Error("Selecione uma versão apresentada para fechar."); const p = provider(); const id = await tenantId(); await p.proposalVersions.update({ ...proposal, status: "accepted" }); const updatedCycle = await p.planningCycles.update({ ...cycle, status: "closed", acceptedProposalVersionId: proposal.id, suggestedReviewAt }); await p.closings.create({ ...timestamps(), tenantId: id, clientId: cycle.clientId, planningCycleId: cycle.id, proposalVersionId: proposal.id, closedAt: new Date().toISOString(), suggestedReviewAt } as ClosingRecord); const client = await p.clients.findById(cycle.clientId); if (client) { const card: PipelineCard = { id: client.id, kind: "client", name: client.name, stage: client.pipelineStage ?? "presented", updatedAt: client.updatedAt }; await movePipelineCard(card, "closed", "Proposta aceita no planejamento"); } return updatedCycle; }
export async function ensurePlanningDemo() { await seedCatalog(); const clients = await listPlanningClients(); const client: Client | undefined = clients.find((item) => item.name === "Rafael Mendes") ?? clients[0]; if (!client) return null; const existing = await listPlanningCycles(client.id); if (existing.some((item) => item.name === "Planejamento familiar 2026")) return client.id; const cycle = await createPlanningCycle({ clientId: client.id, name: "Planejamento familiar 2026", type: "initial", referenceDate: "2026-09-18", observation: "Caso demonstrativo completo." }); const workspace = await planningWorkspace(client.id, cycle.id); if (!workspace.diagnostic) throw new Error("Diagnóstico demonstrativo não foi criado."); const diagnostic = await saveDiagnostic(workspace.diagnostic, { ...draftData, identification: "Rafael Mendes, 39 anos, casado, consultor.", family: "Cônjuge e dois filhos dependentes.", workIncome: "Renda principal e variável informadas pelo cliente.", expenses: "Despesas familiares recorrentes informadas.", assets: "Imóvel residencial e veículo.", reserves: "Reserva de emergência e investimentos declarados.", pensions: "Previdência complementar em avaliação.", debts: "Financiamento em curso.", existingInsurance: "Cobertura atual insuficiente para os objetivos declarados.", health: "Informações de saúde registradas para análise posterior.", goals: "Manutenção do padrão de vida, educação dos filhos e sucessão.", review: "Dados revisados com o cliente.", familyIncome: 24000, monthlyExpense: 14500 }); const completed = await completeDiagnostic(diagnostic); const analysis = await saveBrokerAnalysis({ clientId: client.id, planningCycleId: cycle.id, summary: "Família com dependentes e necessidade de proteção de renda.", priorities: "Padrão de vida, educação e sucessão.", hypotheses: "Combinar proteção de vida e coberturas complementares.", estimatedNeed: 1200000, timeframe: "15 anos", calculationNotes: "Necessidade estimada a validar com a corretora.", recommendations: "Apresentar alternativas e validar composição de cobertura.", pendingQuestions: "Confirmar saldo devedor e coberturas vigentes.", internalNotes: "Uso interno da corretora." }); const v1 = await createProposalVersion(cycle, completed, analysis, "Primeira versão"); await presentProposal(v1); const v2 = await createProposalVersion(cycle, completed, analysis, "Ajuste após reunião"); await presentProposal(v2); await closePlanning(cycle, v2, new Date(Date.now() + 365 * 86400000).toISOString().slice(0, 10)); return client.id; }
