"use client";
import { useState } from "react";
import { addCatalogItem, updateCatalogItem } from "@/application/planning-service";
import { CrudDrawer } from "@/components/crud-drawer";
import type { InsuranceProduct } from "@/domains/core/entities";

type Kind = "insurer" | "product" | "coverageType";
type Item = { id: string; name: string; active: boolean; insurerId?: string };
export function CatalogMaintenance({ catalog, onUpdated }: { catalog: { insurers: Item[]; products: InsuranceProduct[]; coverageTypes: Item[] }; onUpdated: () => Promise<void> }) {
  const [kind, setKind] = useState<Kind>("insurer"); const [editing, setEditing] = useState<Item | "new" | null>(null);
  const rows = kind === "insurer" ? catalog.insurers : kind === "product" ? catalog.products : catalog.coverageTypes;
  const label = kind === "insurer" ? "Seguradoras" : kind === "product" ? "Produtos" : "Tipos de cobertura";
  return <section className="card planning-summary"><p className="eyebrow">CATÁLOGO</p><h3>{label}</h3><p>Itens usados em propostas são mantidos no histórico. Use inativação em vez de exclusão.</p><div className="planning-actions"><label className="crud-field">Cadastro<select value={kind} onChange={(e) => { setKind(e.target.value as Kind); setEditing(null); }}><option value="insurer">Seguradoras</option><option value="product">Produtos</option><option value="coverageType">Tipos de cobertura</option></select></label><button className="button primary" onClick={() => setEditing("new")}>Novo item</button></div><div className="crm-list">{rows.map((item) => <article className="card lead-row" key={item.id}><div><h3>{item.name}</h3><p>{kind === "product" ? `Seguradora: ${catalog.insurers.find((i) => i.id === (item as InsuranceProduct).insurerId)?.name ?? "Não informada"}` : ""}</p></div><div className="lead-actions"><span>{item.active ? "Ativo" : "Inativo"}</span><button className="button secondary" onClick={() => setEditing(item)}>Editar</button></div></article>)}</div>{editing ? <CatalogDrawer kind={kind} item={editing === "new" ? undefined : editing} insurers={catalog.insurers} onClose={() => setEditing(null)} onSaved={async (form) => { if (editing === "new") await addCatalogItem(kind, String(form.get("name")), kind === "product" ? String(form.get("insurerId")) || undefined : undefined); else await updateCatalogItem(kind, { id: editing.id, name: String(form.get("name")), insurerId: kind === "product" ? String(form.get("insurerId")) || undefined : undefined, active: String(form.get("active")) === "true" }); setEditing(null); await onUpdated(); }} /> : null}</section>;
}
function CatalogDrawer({ kind, item, insurers, onClose, onSaved }: { kind: Kind; item?: Item; insurers: Item[]; onClose: () => void; onSaved: (form: FormData) => Promise<void> }) { const title = item ? "Editar item do catálogo" : "Novo item do catálogo"; return <CrudDrawer title={title} description="A inativação preserva vínculos e propostas históricas." onClose={onClose}><form className="crud-form" action={onSaved}><section className="crud-form-section"><h3>{kind === "insurer" ? "Seguradora" : kind === "product" ? "Produto" : "Tipo de cobertura"}</h3><div className="crud-form-grid"><label className="crud-field">Nome<input name="name" required defaultValue={item?.name} /></label>{kind === "product" ? <label className="crud-field">Seguradora<select name="insurerId" required defaultValue={item?.insurerId}><option value="">Selecione</option>{insurers.filter((i) => i.active).map((i) => <option key={i.id} value={i.id}>{i.name}</option>)}</select></label> : null}{item ? <label className="crud-field">Situação<select name="active" defaultValue={item.active ? "true" : "false"}><option value="true">Ativo</option><option value="false">Inativo</option></select></label> : null}</div></section><footer className="crud-actions"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button className="button primary">Salvar</button></footer></form></CrudDrawer>; }
