"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { commercialOverview } from "@/application/commercial-service";
import { saveCommercialBenchmark } from "@/application/commercial-benchmark-service";
import { commercialDashboard, INDICATOR_TYPES, INDICATOR_LABEL, type IndicatorResult } from "@/application/commercial-dashboard";
import { commercialDateParts, activityDate } from "@/application/commercial-aggregations";
import type { CommercialActivityType } from "@/domains/core/entities";
import { useFoundation } from "./foundation-provider";
import { CrudDrawer } from "./crud-drawer";
import { SafeForm } from "./commercial-form";

const months = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"];
const number = (value: number) => new Intl.NumberFormat("pt-BR").format(value);
const percent = (value: number | null) => value === null ? "Sem base" : `${new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 1 }).format(value)}%`;
function IndicatorTable({ rows, onTrace }: { rows: IndicatorResult[]; onTrace: (row: IndicatorResult) => void }) {
  return <div className="indicator-table-wrap"><table className="indicator-table"><thead><tr><th>Indicador</th><th>Benchmark</th><th>Realizado</th><th>Gap</th><th>Atingimento</th><th>Origem</th></tr></thead><tbody>{rows.map((row) => <tr key={row.type}><th>{INDICATOR_LABEL[row.type]}</th><td>{row.target === null ? "Não configurado" : number(row.target)}</td><td>{number(row.actual)}</td><td>{row.gap === null ? "—" : `${row.gap > 0 ? "+" : ""}${number(row.gap)}`}</td><td><span className={row.attainment !== null && row.attainment >= 100 ? "indicator-good" : ""}>{percent(row.attainment)}</span></td><td><button className="button secondary" disabled={!row.activityIds.length} onClick={() => onTrace(row)}>Ver atividades</button></td></tr>)}</tbody></table></div>;
}
export function CommercialDashboard() {
  const { ready, settings } = useFoundation(); const [data, setData] = useState<Awaited<ReturnType<typeof commercialOverview>> | null>(null); const [error, setError] = useState("");
  const now = commercialDateParts(new Date().toISOString())!;
  const [year, setYear] = useState(now.year); const [month, setMonth] = useState(now.month);
  const [consultant, setConsultant] = useState(""); const [origin, setOrigin] = useState("");
  const [tab, setTab] = useState<"month" | "week" | "funnel" | "performance">("month");
  const [editing, setEditing] = useState(false); const [trace, setTrace] = useState<IndicatorResult | null>(null);
  const reload = useCallback(async () => { try { setError(""); setData(await commercialOverview()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar os indicadores."); } }, []);
  useEffect(() => { if (ready && settings) { const timer = window.setTimeout(() => { void reload(); }, 0); return () => window.clearTimeout(timer); } }, [ready, settings, reload]);
  const origins = useMemo(() => { if (!data) return new Map<string, string>(); const labels = new Map(data.parameters.map((item) => [item.id, item.label])); return new Map(data.contacts.map((contact) => [contact.id, labels.get(data.qualifications.find((item) => item.contactId === contact.id)?.sourceId || "") || contact.origin || ""])); }, [data]);
  const contacts = useMemo(() => data?.contacts.map((item) => ({ ...item, origin: origins.get(item.id) })) || [], [data, origins]);
  const report = useMemo(() => data ? commercialDashboard(data.activities, contacts, data.benchmarks, { year, month, consultant: consultant || undefined, origin: origin || undefined }) : null, [data, contacts, year, month, consultant, origin]);
  const years = [...new Set([now.year - 1, now.year, now.year + 1, ...((data?.activities || []).map((item) => commercialDateParts(activityDate(item))?.year).filter((item): item is number => Boolean(item)))])].sort((a, b) => b - a);
  const options = (values: string[]) => [...new Set(values.filter(Boolean))].sort((a, b) => a.localeCompare(b, "pt-BR"));
  const selectedBenchmarks = new Map(data?.benchmarks.filter((item) => item.year === year && item.month === month).map((item) => [item.activityType, item]) || []);
  return <div className="page commercial-page indicator-page"><section className="hero"><div><p className="eyebrow">DOMÍNIO COMERCIAL V2</p><h2>Indicadores comerciais</h2><p>Produção calculada pelas atividades. Benchmarks são as únicas metas configuráveis.</p></div><button className="button secondary" onClick={() => setEditing(true)} disabled={!data}>Configurar benchmarks</button></section>
    {error ? <p role="alert" className="form-error">{error}</p> : null}
    <section className="card indicator-filters" aria-label="Filtros dos indicadores"><label>Ano<select value={year} onChange={(event) => setYear(Number(event.target.value))}>{years.map((value) => <option key={value}>{value}</option>)}</select></label><label>Mês<select value={month} onChange={(event) => setMonth(Number(event.target.value))}>{months.map((name, index) => <option key={name} value={index + 1}>{name}</option>)}</select></label><label>Consultor<select value={consultant} onChange={(event) => setConsultant(event.target.value)}><option value="">Todos</option>{options(contacts.map((item) => item.consultant || "")).map((value) => <option key={value}>{value}</option>)}</select></label><label>Origem<select value={origin} onChange={(event) => setOrigin(event.target.value)}><option value="">Todas</option>{options(contacts.map((item) => item.origin || "")).map((value) => <option key={value}>{value}</option>)}</select></label></section>
    {report ? <><section className="metrics indicator-cards"><div className="card"><span>Atividades no mês</span><strong>{number(report.total)}</strong><p>Registros rastreáveis</p></div><div className="card"><span>Realizadas</span><strong>{number(report.completed)}</strong><p>Data de realização</p></div><div className="card"><span>Planejadas</span><strong>{number(report.planned)}</strong><p>Data agendada</p></div><div className="card"><span>Contatos trabalhados</span><strong>{number(report.contacts)}</strong><p>Contatos distintos</p></div></section>
      <nav className="segmented indicator-tabs" aria-label="Visões do Dashboard">{([ ["month", "Visão do Mês"], ["week", "Visão Semanal"], ["funnel", "Funil"], ["performance", "Performance"] ] as const).map(([key, label]) => <button key={key} className={tab === key ? "active" : ""} onClick={() => setTab(key)}>{label}</button>)}</nav>
      {tab === "month" ? <section className="card indicator-section"><h3>{months[month - 1]} de {year}</h3><p>O resultado de cada linha vem exclusivamente dos registros de atividade do período.</p><IndicatorTable rows={report.monthly} onTrace={setTrace} /></section> : null}
      {tab === "week" ? <section className="indicator-weeks">{report.weekly.map((week) => <article className="card indicator-section" key={week.key}><h3>Semana {week.key}</h3><IndicatorTable rows={week.indicators} onTrace={setTrace} /></article>)}</section> : null}
      {tab === "funnel" ? <section className="card indicator-section"><h3>Funil por contatos distintos</h3><p>Conversão: contatos com atividade nesta etapa após a etapa anterior, divididos pelos contatos da etapa anterior no mês. Sem base, a taxa fica indisponível.</p><div className="funnel-list">{report.funnel.map((step) => <div className="funnel-step" key={step.type}><strong>{INDICATOR_LABEL[step.type]}</strong><span>{number(step.contacts)} contatos</span><span>{step.converted === null ? "Etapa inicial" : `${number(step.converted)} em comum · ${percent(step.conversion)}`}</span><div className="indicator-bar"><i style={{ width: `${report.contacts ? step.contacts / report.contacts * 100 : 0}%` }} /></div></div>)}</div><p className="indicator-bottleneck">Maior gargalo: {report.bottleneck ? `${INDICATOR_LABEL[report.bottleneck.type]} (${percent(report.bottleneck.conversion)})` : "Sem dados suficientes"}</p></section> : null}
      {tab === "performance" ? <section className="card indicator-section"><h3>Performance do período</h3><p>Benchmark zero ou ausente não produz percentual. O gap mostra realizado menos benchmark. Com filtro de consultor ou origem, as metas gerais não são comparadas.</p><div className="performance-grid">{report.monthly.map((row) => <article key={row.type}><b>{INDICATOR_LABEL[row.type]}</b><strong>{number(row.actual)} / {row.target === null ? "—" : number(row.target)}</strong><span>{percent(row.attainment)} · gap {row.gap === null ? "—" : number(row.gap)}</span><div className="indicator-bar"><i style={{ width: `${Math.min(100, row.attainment || 0)}%` }} /></div></article>)}</div></section> : null}</> : <div className="card">Carregando indicadores...</div>}
    {trace && report ? <CrudDrawer title={`Atividades: ${INDICATOR_LABEL[trace.type]}`} description={`${months[month - 1]} de ${year} · ${trace.actual} registros`} onClose={() => setTrace(null)}><section className="crud-form-section"><ol className="hot40-timeline">{report.activities.filter((item) => trace.activityIds.includes(item.id)).map((item) => <li key={item.id}><b>{data?.contacts.find((contact) => contact.id === item.contactId)?.fullName || "Contato"}</b><span>{item.status === "planned" ? "Planejada" : "Realizada"} · {new Date(activityDate(item)!).toLocaleString("pt-BR")}</span>{item.notes ? <p>{item.notes}</p> : null}</li>)}</ol></section><footer className="crud-actions"><button className="button secondary" onClick={() => setTrace(null)}>Fechar</button></footer></CrudDrawer> : null}
    {editing ? <CrudDrawer title="Benchmarks do período" description={`${months[month - 1]} de ${year}. Defina metas por tipo, sem preencher resultados.`} onClose={() => setEditing(false)} size="wide"><SafeForm action={async (form) => { await Promise.all(INDICATOR_TYPES.map((type) => saveCommercialBenchmark({ year, month, activityType: type as CommercialActivityType, weeklyTarget: Number(form.get(`${type}-week`)), monthlyTarget: Number(form.get(`${type}-month`)) }))); await reload(); setEditing(false); }}><section className="crud-form-section"><div className="benchmark-grid"><b>Atividade</b><b>Por semana</b><b>Por mês</b>{INDICATOR_TYPES.map((type) => <div className="benchmark-row" key={type}><span>{INDICATOR_LABEL[type]}</span><input aria-label={`${INDICATOR_LABEL[type]} por semana`} name={`${type}-week`} type="number" min="0" step="1" required defaultValue={selectedBenchmarks.get(type)?.weeklyTarget ?? 0} /><input aria-label={`${INDICATOR_LABEL[type]} por mês`} name={`${type}-month`} type="number" min="0" step="1" required defaultValue={selectedBenchmarks.get(type)?.monthlyTarget ?? 0} /></div>)}</div></section><footer className="crud-actions"><button type="button" className="button secondary" onClick={() => setEditing(false)}>Cancelar</button><button className="button primary">Salvar benchmarks</button></footer></SafeForm></CrudDrawer> : null}
  </div>;
}
