"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ACTIVITY_LABEL, commercialOverview, createCommercialActivity, moveHot40Stage } from "@/application/commercial-service";
import { activityDate } from "@/application/commercial-aggregations";
import type { CommercialActivityType, Contact, Hot40Stage } from "@/domains/core/entities";
import { HOT40_STAGES } from "@/domains/core/entities";
import { isValidQualification } from "@/domains/commercial/qualification";
export { MarketBaseWorkspace } from "./market-base-workspace";
import { useFoundation } from "@/components/foundation-provider";
import { SafeForm } from "./commercial-form";
import { CrudDrawer } from "@/components/crud-drawer";

type Overview = Awaited<ReturnType<typeof commercialOverview>>;
const activityTypes = Object.entries(ACTIVITY_LABEL) as [CommercialActivityType, string][];

function ActivityDrawer({ contact, onClose, onSaved }: { contact: Contact; onClose: () => void; onSaved: () => Promise<void> }) { const [status, setStatus] = useState<"planned" | "completed">("planned"); return <CrudDrawer title="Nova atividade comercial" description="Semana, mês e ano são calculados automaticamente a partir da data informada." onClose={onClose}><SafeForm action={async (form) => { const status = String(form.get("status")); const date = String(form.get("date")); await createCommercialActivity({ contactId: contact.id, type: String(form.get("type")) as CommercialActivityType, status: status as "planned" | "completed", ...(status === "completed" ? { completedAt: date } : { scheduledAt: date }), notes: String(form.get("notes") || "") }); await onSaved(); onClose(); }}><section className="crud-form-section"><h3>{contact.fullName}</h3><div className="crud-form-grid"><label className="crud-field">Tipo<select name="type">{activityTypes.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="crud-field">Situação<select name="status" value={status} onChange={(event) => setStatus(event.target.value as "planned" | "completed")}><option value="planned">Planejada</option><option value="completed">Realizada</option></select></label><label className="crud-field full">{status === "planned" ? "Data agendada" : "Data realizada"}<input name="date" type="datetime-local" required /></label><label className="crud-field full">Observações<textarea name="notes" /></label></div></section><footer className="crud-actions"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button className="button primary">Salvar atividade</button></footer></SafeForm></CrudDrawer>; }

function useOverview() { const { ready, settings } = useFoundation(); const [data, setData] = useState<Overview | null>(null); const [error, setError] = useState(""); const reload = useCallback(async () => { try { setError(""); setData(await commercialOverview()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar o domínio comercial."); } }, []); useEffect(() => { if (!ready || !settings) return; const timer = window.setTimeout(() => { void reload(); }, 0); return () => window.clearTimeout(timer); }, [reload, ready, settings]); return { data, error, reload }; }
function Empty({ children }: { children: React.ReactNode }) { return <div className="empty"><h2>Aguardando dados comerciais</h2><p>{children}</p></div>; }
export function CommercialDashboard() { const { data, error } = useOverview(); const completed = data?.activities.filter((item) => item.status === "completed").length ?? 0; return <div className="page commercial-page"><section className="hero"><div><p className="eyebrow">DOMÍNIO COMERCIAL V2</p><h2>Visão comercial operacional</h2><p>Os indicadores vêm de contatos e atividades estruturadas. Não há campos manuais para semana, mês ou ano.</p></div></section>{error ? <p className="form-error">{error}</p> : null}<section className="metrics commercial-metrics"><div className="card"><span>Contatos</span><strong>{data?.contacts.length ?? "—"}</strong><p>base canônica</p></div><div className="card"><span>Qualificados</span><strong>{data?.qualifications.filter(isValidQualification).length ?? "—"}</strong><p>sem duplicidade</p></div><div className="card"><span>HOT40 ativos</span><strong>{data?.memberships.filter((item) => item.status === "active").length ?? "—"}</strong><p>acompanhamento</p></div><div className="card"><span>Atividades</span><strong>{data?.activities.length ?? "—"}</strong><p>{completed} realizadas</p></div><div className="card"><span>Meta ativa</span><strong>{data?.goals[0]?.target ?? "—"}</strong><p>{data?.goals[0]?.name ?? "sem meta"}</p></div></section><section className="commercial-note"><b>Metis contextual</b><span>A assistente permanece disponível dentro do contexto do cliente quando esse fluxo precisar de apoio profissional.</span></section></div>; }
const stageLabel: Record<Hot40Stage, string> = { ab_phone: "ABPhone - Ligações", approach_scheduled: "Abordagem Marcada", approach_completed: "Abordagem Realizada", closing_scheduled: "Fechamento Marcado", closing_completed: "Fechamento Realizado", proposal: "Proposta" };
const when = (value?: string) => value ? new Date(value).toLocaleString("pt-BR") : "Não registrada";
function elapsed(value?: string) { if (!value) return "Sem interação"; const days = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 86400000)); return days === 0 ? "Hoje" : `${days} dia${days === 1 ? "" : "s"}`; }
export function Hot40Workspace() {
  const { data, error, reload } = useOverview();
  const [view, setView] = useState<"list" | "kanban">("list");
  const [actionError, setActionError] = useState("");
  const [selected, setSelected] = useState<Contact | null>(null);
  const [details, setDetails] = useState<Contact | null>(null);
  const [moving, setMoving] = useState<{ contact: Contact; stage: Hot40Stage } | null>(null);
  const contacts = useMemo(() => new Map(data?.contacts.map((item) => [item.id, item]) ?? []), [data]);
  if (!data) return <div className="page"><Empty>{error || "Carregando HOT40."}</Empty></div>;
  const members = data.memberships.filter((item) => item.status === "active" && contacts.get(item.contactId)?.commercialStage === "hot40");
  const activitiesFor = (id: string) => data.activities.filter((item) => item.contactId === id && !item.deletedAt);
  const nextFor = (id: string) => activitiesFor(id).filter((item) => item.status === "planned" && item.scheduledAt).sort((a, b) => a.scheduledAt!.localeCompare(b.scheduledAt!))[0];
  const lastFor = (id: string) => activitiesFor(id).filter((item) => item.status === "completed" && item.completedAt).sort((a, b) => b.completedAt!.localeCompare(a.completedAt!))[0];
  const originFor = (id: string) => { const qualification = data.qualifications.find((item) => item.contactId === id); return data.parameters.find((item) => item.id === qualification?.sourceId)?.label || contacts.get(id)?.origin || "Não informada"; };
  const move = async (contact: Contact, stage: Hot40Stage, notes: string) => { try { setActionError(""); await moveHot40Stage(contact.id, stage, notes); await reload(); setMoving(null); } catch (cause) { setActionError(cause instanceof Error ? cause.message : "Não foi possível mover o contato."); } };
  const actions = (contact: Contact) => <div className="commercial-actions"><button className="button secondary" onClick={() => setSelected(contact)}>Nova atividade</button><button className="button secondary" onClick={() => setDetails(contact)}>Detalhes</button></div>;
  return <div className="page commercial-page"><section className="hero"><div><p className="eyebrow">HOT40</p><h2>Carteira prioritária</h2><p>{members.length} contatos ativos. Lista e Kanban compartilham o mesmo registro.</p></div><div className="segmented"><button className={view === "list" ? "active" : ""} onClick={() => setView("list")}>Lista</button><button className={view === "kanban" ? "active" : ""} onClick={() => setView("kanban")}>Kanban</button></div></section>{error ? <p role="alert" className="form-error">{error}</p> : null}{actionError ? <p role="alert" className="form-error">{actionError}</p> : null}
    {view === "list" ? <section className="commercial-list card">{members.length ? members.map((member) => { const contact = contacts.get(member.contactId)!; const next = nextFor(contact.id); const last = lastFor(contact.id); return <article className="commercial-row hot40-row" key={member.id}><div className="hot40-summary"><b>{contact.fullName}</b><div className="hot40-facts"><span>Etapa: {stageLabel[member.stage || "ab_phone"]}</span><span>Próxima ação: {next ? ACTIVITY_LABEL[next.type] : "Não planejada"}</span><span>Data/hora: {when(next?.scheduledAt)}</span><span>Última interação: {last ? `${ACTIVITY_LABEL[last.type]} · ${when(last.completedAt)}` : "Não registrada"}</span><span>Tempo parado: {elapsed(last?.completedAt || member.stageChangedAt || member.enteredAt)}</span><span>Origem: {originFor(contact.id)}</span></div></div>{actions(contact)}</article>; }) : <Empty>Adicione contatos qualificados ao HOT40.</Empty>}</section> : <section className="commercial-kanban hot40-kanban">{HOT40_STAGES.map((stage) => <div className="card hot40-column" key={stage} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); const contact = contacts.get(event.dataTransfer.getData("text/plain")); if (contact && members.some((member) => member.contactId === contact.id && (member.stage || "ab_phone") !== stage)) setMoving({ contact, stage }); }}><h3>{stageLabel[stage]} <small>{members.filter((member) => (member.stage || "ab_phone") === stage).length}</small></h3>{members.filter((member) => (member.stage || "ab_phone") === stage).map((member) => { const contact = contacts.get(member.contactId)!; const next = nextFor(contact.id); return <article className="kanban-card" key={member.id} draggable onDragStart={(event) => event.dataTransfer.setData("text/plain", contact.id)}><b>{contact.fullName}</b><p>Próxima: {next ? `${ACTIVITY_LABEL[next.type]} · ${when(next.scheduledAt)}` : "Não planejada"}</p>{actions(contact)}<label className="hot40-move">Mover para<select aria-label={`Mover ${contact.fullName} para etapa`} value={stage} onChange={(event) => setMoving({ contact, stage: event.target.value as Hot40Stage })}>{HOT40_STAGES.map((target) => <option key={target} value={target}>{stageLabel[target]}</option>)}</select></label></article>; })}</div>)}</section>}
    {selected ? <ActivityDrawer contact={selected} onClose={() => setSelected(null)} onSaved={reload} /> : null}
    {moving ? <CrudDrawer title="Mover etapa" description={`${moving.contact.fullName} → ${stageLabel[moving.stage]}`} onClose={() => setMoving(null)}><SafeForm action={async (form) => move(moving.contact, moving.stage, String(form.get("notes") || ""))}><section className="crud-form-section"><label className="crud-field">Contexto da movimentação<textarea name="notes" maxLength={2000} required /></label></section><footer className="crud-actions"><button type="button" className="button secondary" onClick={() => setMoving(null)}>Cancelar</button><button className="button primary">Confirmar etapa</button></footer></SafeForm></CrudDrawer> : null}
    {details ? <CrudDrawer title={details.fullName} description="Histórico comercial do contato" onClose={() => setDetails(null)}><section className="crud-form-section"><h3>Próxima ação</h3><p>{nextFor(details.id) ? `${ACTIVITY_LABEL[nextFor(details.id)!.type]} · ${when(nextFor(details.id)!.scheduledAt)}` : "Nenhuma atividade planejada."}</p><h3>Timeline</h3><ol className="hot40-timeline">{[...activitiesFor(details.id).map((item) => ({ id: item.id, date: activityDate(item) || item.createdAt, label: `${ACTIVITY_LABEL[item.type]} · ${item.status === "completed" ? "Realizada" : item.status === "planned" ? "Planejada" : "Cancelada"}`, notes: item.notes })), ...data.stageEvents.filter((item) => item.contactId === details.id).map((item) => ({ id: item.id, date: item.occurredAt, label: `Etapa: ${stageLabel[item.fromStage || "ab_phone"]} → ${stageLabel[item.toStage]}`, notes: item.notes }))].sort((a, b) => b.date.localeCompare(a.date)).map((event) => <li key={event.id}><b>{event.label}</b><span>{when(event.date)}</span>{event.notes ? <p>{event.notes}</p> : null}</li>)}</ol></section><footer className="crud-actions"><button className="button secondary" onClick={() => setDetails(null)}>Fechar</button></footer></CrudDrawer> : null}
  </div>;
}
export function CommercialClientsWorkspace() { const { data } = useOverview(); if (!data) return <div className="page"><Empty>Carregando clientes do novo domínio.</Empty></div>; const clients = data.contacts.filter((contact) => contact.commercialStage === "client"); return <div className="page commercial-page"><section className="hero"><div><p className="eyebrow">CLIENTES</p><h2>Clientes do domínio comercial</h2><p>São os mesmos contatos canônicos que avançaram no processo, sem novo cadastro.</p></div></section><section className="commercial-list card">{clients.length ? clients.map((contact) => <article className="commercial-row" key={contact.id}><div><b>{contact.fullName}</b><p>{contact.email || contact.phone || "Dados de contato a complementar"}</p></div><span className="commercial-stage">Cliente</span></article>) : <Empty>Quando um contato avançar no HOT40, ele aparecerá aqui usando o mesmo cadastro.</Empty>}</section></div>; }
