"use client";
import { useCallback, useEffect, useState } from "react";
import { COMMERCIAL_PARAMETER_GROUPS, type CommercialParameter, type CommercialParameterGroup } from "@/domains/core/entities";
import { PARAMETER_LABELS } from "@/domains/commercial/qualification";
import { listCommercialParameters, saveCommercialParameter } from "@/application/commercial-parameters-service";
import { useFoundation } from "./foundation-provider";
import { operationalOverview, saveAttentionPolicy } from "@/application/operational-service";
import { DEFAULT_ATTENTION_POLICY, type AttentionPolicy } from "@/application/commercial-attention";
import { SettingsForm } from "./settings-form";
import { SafeForm } from "./commercial-form";
import { CrudDrawer } from "./crud-drawer";

export function CommercialSettingsWorkspace() {
  const [tab, setTab] = useState<"parameters" | "brand" | "attention">("parameters");
  return <><div className="settings-tabs segmented" aria-label="Seções de configurações"><button className={tab === "parameters" ? "active" : ""} onClick={() => setTab("parameters")}>Parâmetros comerciais</button><button className={tab === "attention" ? "active" : ""} onClick={() => setTab("attention")}>Alertas</button><button className={tab === "brand" ? "active" : ""} onClick={() => setTab("brand")}>Marca da corretora</button></div>{tab === "brand" ? <SettingsForm /> : tab === "attention" ? <AttentionSettings /> : <ParametersWorkspace />}</>;
}
function ParametersWorkspace() {
  const { ready, settings } = useFoundation(); const [parameters, setParameters] = useState<CommercialParameter[] | null>(null); const [group, setGroup] = useState<CommercialParameterGroup>("source");
  const [drawer, setDrawer] = useState<{ item?: CommercialParameter } | null>(null); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const reload = useCallback(async () => { setParameters(await listCommercialParameters()); }, []);
  useEffect(() => { if (!ready || !settings) return; let cancelled = false; listCommercialParameters().then((data) => { if (!cancelled) setParameters(data); }).catch((cause) => { if (!cancelled) setError(cause instanceof Error ? cause.message : "Não foi possível carregar os parâmetros."); }); return () => { cancelled = true; }; }, [ready, settings]);
  const toggle = async (item: CommercialParameter) => { if (busy) return; setBusy(true); setError(""); try { await saveCommercialParameter({ ...item, active: !item.active }); await reload(); setNotice(item.active ? "Parâmetro desativado. Os cadastros anteriores mantêm a referência." : "Parâmetro ativado."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível atualizar o parâmetro."); } finally { setBusy(false); } };
  const options = parameters?.filter((item) => item.group === group) || [];
  return <div className="page commercial-page"><section className="hero"><div><p className="eyebrow">CONFIGURAÇÕES COMERCIAIS</p><h2>Os critérios da sua operação</h2><p>Edite as opções usadas na qualificação. Desativar uma opção preserva os cadastros que já a utilizaram.</p></div><button className="button primary" disabled={!parameters} onClick={() => setDrawer({})}>Novo parâmetro</button></section>
    {notice ? <p className="market-feedback" role="status">{notice}</p> : null}{error ? <p className="market-error" role="alert">{error}</p> : null}
    <section className="card parameter-group"><label>Grupo de parâmetros<select value={group} onChange={(event) => setGroup(event.target.value as CommercialParameterGroup)}>{COMMERCIAL_PARAMETER_GROUPS.map((key) => <option key={key} value={key}>{PARAMETER_LABELS[key]}</option>)}</select></label><p className="market-hint">As opções iniciais vieram da aba Matriz. Nenhuma pontuação automática é aplicada.</p></section>
    <section className="card commercial-list"><div className="commercial-list-head"><h3>{PARAMETER_LABELS[group]}</h3><span>{options.filter((item) => item.active).length} ativos</span></div>{options.map((item) => <article className="commercial-row" key={item.id}><div><b>{item.label}</b><div className="commercial-pills"><span className={item.active ? "qualification-qualified" : "qualification-pending"}>{item.active ? "Ativo" : "Inativo"}</span><span>Ordem {item.order}</span></div></div><div className="commercial-actions"><button className="button secondary" onClick={() => setDrawer({ item })}>Editar</button><button className="button secondary" disabled={busy} onClick={() => { void toggle(item); }}>{item.active ? "Desativar" : "Ativar"}</button></div></article>)}{!options.length ? <div className="empty" role="status">{parameters ? "Cadastre o primeiro parâmetro deste grupo." : "Carregando parâmetros..."}</div> : null}</section>
    {drawer ? <CrudDrawer title={drawer.item ? "Editar parâmetro" : "Novo parâmetro"} description={PARAMETER_LABELS[group]} onClose={() => setDrawer(null)}><SafeForm action={async (form) => { await saveCommercialParameter({ id: drawer.item?.id, group, label: String(form.get("label") || ""), order: Number(form.get("order")), active: form.get("active") === "on" }); await reload(); setNotice("Parâmetro salvo. A qualificação já utiliza a configuração atualizada."); setDrawer(null); }}><section className="crud-form-section"><div className="crud-form-grid"><label className="crud-field full">Nome da opção<input name="label" defaultValue={drawer.item?.label} required maxLength={120} autoFocus /></label><label className="crud-field">Ordem de exibição<input name="order" type="number" min="0" step="1" defaultValue={drawer.item?.order ?? (options.length ? Math.max(...options.map((item) => item.order)) + 1 : 0)} required /></label><label className="parameter-active"><input name="active" type="checkbox" defaultChecked={drawer.item?.active ?? true} />Ativo para novas seleções</label></div></section><footer className="crud-actions"><button type="button" className="button secondary" onClick={() => setDrawer(null)}>Cancelar</button><button className="button primary">Salvar parâmetro</button></footer></SafeForm></CrudDrawer> : null}
  </div>;
}

function AttentionSettings() {
  const { ready, settings } = useFoundation(); const [policy, setPolicy] = useState<AttentionPolicy | null>(null); const [notice, setNotice] = useState("");
  useEffect(() => { if (ready && settings) { void operationalOverview().then((data) => setPolicy(data.policy)).catch(() => setPolicy(DEFAULT_ATTENTION_POLICY)); } }, [ready, settings]);
  const fields = [["stalledDays", "HOT40 parado, dias"], ["criticalStalledDays", "HOT40 crítico, dias"], ["criticalOverdueHours", "Atividade crítica, horas"], ["funnelMinimumContacts", "Base mínima do funil"], ["funnelMaximumConversion", "Conversão máxima para gargalo, %"]] as const;
  return <div className="page commercial-page"><section className="hero"><div><p className="eyebrow">CONFIGURAÇÕES COMERCIAIS</p><h2>Política de atenção</h2><p>Os limites são aplicados aos dados comerciais já registrados.</p></div></section>{notice ? <p role="status">{notice}</p> : null}{policy ? <section className="card indicator-section"><SafeForm action={async (form) => { const next = Object.fromEntries(fields.map(([key]) => [key, Number(form.get(key))])) as AttentionPolicy; await saveAttentionPolicy(next); setPolicy(next); setNotice("Política salva. Os alertas serão recalculados ao abrir ou atualizar a Agenda."); }}><div className="crud-form-grid">{fields.map(([key, label]) => <label className="crud-field" key={key}>{label}<input name={key} type="number" min="0" max={key === "funnelMaximumConversion" ? "100" : undefined} step="1" defaultValue={policy[key]} required /></label>)}</div><button className="button primary">Salvar política</button></SafeForm></section> : <p>Carregando política...</p>}</div>;
}
