"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

type Category = "Fluxo principal" | "Rotina de apoio";
type Entry = {
  id: string; number: string; category: Category; name: string; objective: string; what: string; why: string; who: string; when: string; where: string; how: string; howMuch: string;
  steps: string[]; done: string; next: string; errors: string[]; keywords: string[]; href?: string; button?: string;
};

const entry = (data: Entry) => data;

const entries: Entry[] = [
  entry({ id: "dashboard", number: "00", category: "Rotina de apoio", name: "Dashboard", objective: "Acompanhar o panorama comercial e operacional, sem substituir a consulta aos registros de origem.", what: "Indicadores de funil, aging, evolução, carteira e atalhos.", why: "Ajuda a priorizar atendimentos e identificar oportunidades paradas.", who: "Consultor, gestor comercial ou responsável pela corretora.", when: "No início do dia, antes de reuniões e em revisões periódicas.", where: "Menu Dashboard.", how: "Leia os indicadores e abra o módulo de origem sempre que precisar agir.", howMuch: "Não se aplica diretamente.", steps: ["Abra Dashboard.", "Observe funil, aging, evolução e carteira.", "Use os atalhos ou filtros para chegar ao atendimento que exige ação."], done: "Os indicadores foram analisados e as prioridades do período ficaram claras.", next: "Siga para Kanban ou para o módulo indicado pelo dado que precisa de ação.", errors: ["Tratar indicador como cadastro.", "Confundir capital segurado com investimento ou rendimento."], keywords: ["indicadores", "funil", "aging", "evolução", "carteira"], href: "/", button: "Abrir Dashboard" }),
  entry({ id: "lead", number: "01", category: "Fluxo principal", name: "Lead", objective: "Registrar a oportunidade inicial e preservar o contexto do primeiro contato.", what: "Cadastro da oportunidade, origem, contato, próxima ação e observações.", why: "Evita perda de contatos e organiza a abordagem comercial.", who: "Consultor ou pessoa responsável pela captação.", when: "Assim que houver uma oportunidade identificada.", where: "Menu Leads.", how: "Crie o lead, informe somente dados conhecidos e defina uma próxima ação.", howMuch: "Não se aplica diretamente.", steps: ["Abra Leads e selecione Novo lead.", "Informe nome, contato disponível, origem, próxima ação e observação.", "Salve e acompanhe a evolução no Kanban.", "Converta para cliente quando o atendimento estiver qualificado."], done: "O lead foi convertido, descartado ou permanece ativo com próxima ação definida.", next: "Acompanhe-o no Kanban ou faça a conversão para Cliente.", errors: ["Usar observação no lugar da próxima ação.", "Arquivar um lead que ainda precisa de retorno."], keywords: ["origem", "conversão", "arquivar", "restaurar", "próxima ação"], href: "/leads", button: "Ir para Leads" }),
  entry({ id: "kanban", number: "02", category: "Fluxo principal", name: "Kanban", objective: "Representar o estado real de cada atendimento no pipeline comercial.", what: "Quadro visual de oportunidades por estágio.", why: "Torna o trabalho comercial visível e alimenta indicadores pelo histórico.", who: "Consultor e gestão comercial.", when: "Sempre que houver evolução, bloqueio ou mudança real no atendimento.", where: "Menu Kanban.", how: "Mova o cartão para o estágio atual e mantenha a próxima ação atualizada.", howMuch: "Não se aplica diretamente.", steps: ["Abra Kanban.", "Localize o lead ou cliente.", "Atualize o estágio conforme a evolução real.", "Confirme se a próxima ação continua clara."], done: "A coluna representa a situação atual e não há movimentação fictícia.", next: "Converta o lead quando qualificado ou avance para o planejamento do cliente.", errors: ["Mover para Pronto para apresentação sem proposta revisada.", "Usar Kanban sem atualizar a próxima ação."], keywords: ["pipeline", "novo lead", "a calcular", "apresentado", "fechado", "não fechado"], href: "/kanban", button: "Ir para Kanban" }),
  entry({ id: "cliente", number: "03", category: "Fluxo principal", name: "Cliente", objective: "Manter o cadastro permanente da pessoa atendida e seus vínculos históricos.", what: "Cadastro de cliente, contato, dados profissionais, endereço e observações.", why: "É a referência permanente para planejamentos, propostas e carteira.", who: "Consultor responsável pelo atendimento.", when: "Na conversão de um lead qualificado ou no início de atendimento direto.", where: "Menu Clientes.", how: "Crie ou converta o cadastro e complete apenas as informações disponíveis.", howMuch: "Não se aplica diretamente.", steps: ["Abra Clientes ou converta um lead.", "Preencha os campos conhecidos e salve.", "Abra o dashboard individual para acessar planejamentos e histórico.", "Inative, em vez de excluir, quando não houver atendimento ativo."], done: "O cliente está identificado e pronto para receber planejamentos, sem apagar histórico.", next: "Crie ou abra um Planejamento para registrar o contexto do atendimento.", errors: ["Confundir Cliente com fotografia financeira atual.", "Sobrescrever dados que pertencem a planejamento histórico."], keywords: ["inativar", "reativar", "dashboard do cliente", "conversão"], href: "/clientes", button: "Ir para Clientes" }),
  entry({ id: "diagnostico", number: "04", category: "Fluxo principal", name: "Diagnóstico", objective: "Registrar o levantamento estruturado e os dados declarados pelo cliente.", what: "Etapas de identificação, família, renda, despesas, patrimônio, seguros, saúde, objetivos e revisão.", why: "Cria a fotografia do período para orientar o planejamento.", who: "Consultor, com base no que foi informado pelo cliente.", when: "Depois de existir cliente e contexto de planejamento.", where: "Menu Diagnósticos ou área do Planejamento.", how: "Preencha por etapas, revise as respostas e conclua quando o levantamento estiver conferido.", howMuch: "Não se aplica diretamente.", steps: ["Selecione cliente e planejamento.", "Preencha as etapas sem completar lacunas por suposição.", "Saia e retorne quando necessário, pois há salvamento automático.", "Revise e conclua o diagnóstico."], done: "O diagnóstico foi revisado, concluído e permanece consultável no histórico.", next: "Registre a Análise profissional e prepare a Proposta quando houver informações suficientes.", errors: ["Registrar inferência como declaração do cliente.", "Inventar renda, patrimônio, saúde ou composição familiar."], keywords: ["autosave", "reabrir", "saúde", "objetivos", "dados declarados"], href: "/diagnosticos", button: "Ir para Diagnósticos" }),
  entry({ id: "planejamento", number: "05", category: "Fluxo principal", name: "Planejamento", objective: "Organizar o contexto estratégico e a data de referência de um ciclo de atendimento.", what: "Contexto com nome, tipo, data de referência, status e observações.", why: "Separa fotografias de momentos diferentes e preserva o histórico.", who: "Consultor responsável pelo caso.", when: "Antes do diagnóstico ou quando surgir revisão, replanejamento ou simulação.", where: "Menu Planejamentos e dashboard do cliente.", how: "Crie o planejamento e escolha Inicial, Revisão, Replanejamento ou Simulação.", howMuch: "Não se aplica diretamente.", steps: ["Selecione o cliente.", "Escolha Novo planejamento.", "Informe nome, tipo, data de referência e observação.", "Continue o atual se o contexto não mudou; crie outro se mudou."], done: "Existe um planejamento com contexto definido e vínculos preservados.", next: "Preencha Diagnóstico e depois Análise profissional.", errors: ["Confundir Planejamento com Proposta.", "Criar versão quando a fotografia mudou e o correto seria novo planejamento."], keywords: ["inicial", "revisão", "replanejamento", "simulação", "data de referência"], href: "/planejamentos", button: "Ir para Planejamentos" }),
  entry({ id: "analise-profissional", number: "06", category: "Fluxo principal", name: "Análise profissional", objective: "Registrar a interpretação do consultor separadamente dos dados declarados pelo cliente.", what: "Resumo, necessidades, prioridades, objetivos, estratégia, necessidade estimada, pendências e notas internas.", why: "Dá rastreabilidade à análise profissional sem alterar o diagnóstico.", who: "Consultor ou corretor responsável.", when: "Após o levantamento e antes da proposta, ou em revisão técnica.", where: "Área do Planejamento.", how: "Preencha cada seção com julgamento profissional claramente identificável como análise.", howMuch: "Não se aplica diretamente.", steps: ["Abra o planejamento.", "Acesse Análise profissional.", "Registre necessidades, prioridades, estratégia e perguntas pendentes.", "Salve antes de montar ou revisar proposta."], done: "A leitura profissional está registrada e não se mistura às respostas do cliente.", next: "Monte a Proposta ou use Metis como apoio, com revisão profissional.", errors: ["Copiar sugestão de IA como fato sem revisão.", "Alterar dado declarado para refletir interpretação profissional."], keywords: ["prioridades", "estratégia", "necessidade estimada", "notas internas"], href: "/planejamentos", button: "Ir para Planejamentos" }),
  entry({ id: "catalogo", number: "A1", category: "Rotina de apoio", name: "Catálogo", objective: "Manter os dados mestres usados nas propostas sem criar um cadastro paralelo dentro delas.", what: "Seguradoras, produtos e tipos de cobertura.", why: "Padroniza as opções e garante Produto associado à Seguradora.", who: "Administrador ou consultor autorizado.", when: "Ao preparar a base operacional ou quando houver mudança real no catálogo.", where: "Menu Catálogo.", how: "Crie, edite, inative ou reative cada item no drawer de manutenção.", howMuch: "Não se aplica diretamente.", steps: ["Cadastre a seguradora.", "Cadastre produto vinculado à seguradora.", "Cadastre tipo de cobertura.", "Inative itens que não devem entrar em novos casos, sem destruir histórico."], done: "Os dados mestres necessários estão ativos e a associação Produto → Seguradora está correta.", next: "Use as opções na manutenção de Coberturas da Proposta.", errors: ["Cadastrar seguradora, produto ou tipo dentro de Propostas.", "Excluir item usado historicamente em vez de inativar."], keywords: ["seguradora", "produto", "tipo de cobertura", "inativar", "reativar"], href: "/catalogo", button: "Ir para Catálogo" }),
  entry({ id: "proposta", number: "07", category: "Fluxo principal", name: "Proposta e coberturas", objective: "Montar solução de proteção rastreável, com versões e coberturas vinculadas ao planejamento.", what: "Versão em rascunho com coberturas, objetivos, capital, prêmio, vigência, descrição e observações.", why: "Permite comparar alternativas sem apagar o que já foi apresentado ou aceito.", who: "Consultor responsável pela recomendação.", when: "Depois do diagnóstico e análise profissional, ou em revisão.", where: "Menu Propostas e planejamento do cliente.", how: "Crie em draft, adicione coberturas do Catálogo, salve e duplique para mudanças relevantes.", howMuch: "Prêmio e capital são informados na proposta. Não há custo direto do sistema.", steps: ["Crie versão em draft vinculada ao planejamento.", "Adicione cobertura usando seguradora, produto e tipo do Catálogo.", "Informe capital, prêmio, vigência, objetivo, descrição e observação.", "Reordene as coberturas e salve.", "Duplique a versão para uma alternativa."], done: "A versão em rascunho está completa e os totais representam suas coberturas.", next: "Use Metis para revisão opcional ou marque a versão como apresentada.", errors: ["Editar versão apresentada, aceita ou substituída.", "Tratar capital segurado como investimento ou rendimento.", "Desrespeitar a relação entre produto e seguradora."], keywords: ["draft", "coberturas", "capital segurado", "prêmio", "duplicar", "versão"], href: "/propostas", button: "Ir para Propostas" }),
  entry({ id: "metis", number: "08", category: "Fluxo principal", name: "Metis", objective: "Apoiar o consultor no contexto do cliente, diagnóstico ou versão de proposta selecionada.", what: "Ações Analisar diagnóstico, Preparar próxima reunião e Revisar proposta.", why: "Ajuda a identificar lacunas e revisar coerência, sem substituir decisão profissional.", who: "Consultor ou corretor que revisará o resultado.", when: "Após registrar dados estruturados e antes de decidir ações comerciais.", where: "Dashboard do cliente e contexto da proposta. Não existe rota genérica.", how: "Escolha a ação adequada, confira a evidência de sanitização e revise criticamente a resposta.", howMuch: "O consumo de IA é controlado pelo ambiente. Não há cobrança exibida nesta tela.", steps: ["Abra cliente e planejamento.", "Use Analisar diagnóstico para lacunas.", "Use Preparar próxima reunião para perguntas contextualizadas.", "Use Revisar proposta na versão específica.", "Revise o resultado antes de agir."], done: "O resultado foi revisado pelo consultor e permaneceu no histórico da Metis.", next: "Atualize dados, análise ou proposta somente por decisão profissional explícita.", errors: ["Tratar resposta como decisão automática.", "Esperar que Metis feche proposta ou altere cadastro.", "Usar análise como regra confirmada da seguradora."], keywords: ["ia", "analisar diagnóstico", "preparar próxima reunião", "revisar proposta", "sanitização"] }),
  entry({ id: "apresentacao", number: "09", category: "Fluxo principal", name: "Apresentação", objective: "Registrar a versão levada ao cliente e preservar essa fotografia comercial.", what: "Marcação de apresentação e geração de visualização ou PDF comercial.", why: "Protege a versão apresentada e evita reescrever histórico comercial.", who: "Consultor responsável pela apresentação.", when: "Quando o rascunho foi revisado e está pronto para ser apresentado.", where: "Menu Propostas.", how: "Selecione versão, confirme apresentação e gere documentos quando necessário.", howMuch: "Não se aplica diretamente.", steps: ["Abra o rascunho revisado.", "Confirme Marcar como apresentada.", "Gere ou abra apresentação e PDF comercial.", "Para mudar solução, parta de nova versão."], done: "A versão apresentada está identificada e protegida no histórico.", next: "Aguarde a decisão do cliente ou siga para Fechamento.", errors: ["Sobrescrever versão apresentada.", "Alterar solução sem criar nova versão."], keywords: ["apresentada", "pdf comercial", "histórico", "imutável"], href: "/propostas", button: "Ir para Propostas" }),
  entry({ id: "fechamento", number: "10", category: "Fluxo principal", name: "Fechamento", objective: "Registrar aceite em versão específica e refletir a contratação nos dados derivados.", what: "Aceite ou fechamento associado a uma versão apresentada.", why: "Mantém origem de capital, prêmio e coberturas da proteção contratada.", who: "Consultor responsável.", when: "Após decisão favorável do cliente sobre uma versão apresentada.", where: "Contexto do Planejamento ou Proposta.", how: "Selecione a versão correta, registre fechamento e confira os dados apresentados.", howMuch: "Valores são derivados da versão aceita e não são digitados novamente na Carteira.", steps: ["Confirme a versão escolhida.", "Registre aceite ou fechamento.", "Confira capital, prêmio e coberturas.", "Consulte Carteira e Dashboard."], done: "A versão aceita está preservada e o fechamento aponta para ela.", next: "O cliente passa a ser acompanhado automaticamente na Carteira.", errors: ["Fechar versão diferente da apresentada.", "Editar valores históricos após aceite."], keywords: ["aceite", "fechado", "proposta aceita", "capital", "prêmio"], href: "/planejamentos", button: "Ir para Planejamentos" }),
  entry({ id: "carteira", number: "11", category: "Fluxo principal", name: "Carteira", objective: "Acompanhar clientes com proteção contratada a partir das propostas aceitas ou fechadas.", what: "Visão derivada de cliente, planejamento, proposta aceita, coberturas, capital, prêmio, vigência e revisão.", why: "Permite acompanhar contratos ativos sem criar fonte paralela de verdade.", who: "Consultor e gestão da corretora.", when: "Depois de fechamentos e nas rotinas de acompanhamento.", where: "Menu Carteira.", how: "Pesquise, filtre, abra registros de origem e use Iniciar revisão quando necessário.", howMuch: "Prêmio mensal e anual são calculados pela proposta aceita.", steps: ["Abra Carteira.", "Pesquise ou filtre pelos critérios disponíveis.", "Abra cliente, planejamento ou proposta aceita.", "Use Iniciar revisão para novo contexto."], done: "A proteção contratada está acompanhada e a próxima revisão foi considerada.", next: "Inicie Revisão ou Replanejamento quando houver nova necessidade.", errors: ["Cadastrar manualmente na Carteira algo não fechado.", "Alterar proposta aceita para representar revisão posterior."], keywords: ["contrato", "proteção contratada", "prêmio anual", "vigência", "próxima revisão"], href: "/carteira", button: "Ir para Carteira" }),
  entry({ id: "relatorios", number: "12", category: "Fluxo principal", name: "Relatórios", objective: "Localizar, abrir e baixar documentos já gerados no atendimento.", what: "Central de diagnóstico, relatório interno, apresentação e PDF comercial.", why: "Permite reutilizar documentos e preservar sua origem histórica.", who: "Consultor responsável.", when: "Depois de gerar documentos e quando precisar consultá-los novamente.", where: "Menu Relatórios.", how: "Localize pelo cliente, abra snapshot, baixe ou siga ao registro de origem.", howMuch: "Não se aplica diretamente.", steps: ["Abra Relatórios.", "Localize o documento pelo cliente ou contexto.", "Abra visualização e confirme a origem.", "Baixe novamente sem recalcular histórico."], done: "O documento é reproduzido pelo snapshot correspondente.", next: "Retorne ao registro de origem ou gere novo documento no fluxo apropriado.", errors: ["Esperar que alterações atuais mudem relatório antigo.", "Confundir diagnóstico com apresentação comercial."], keywords: ["snapshot", "pdf", "diagnóstico interno", "apresentação comercial", "download"], href: "/relatorios", button: "Ir para Relatórios" }),
  entry({ id: "revisao", number: "13", category: "Fluxo principal", name: "Revisão e replanejamento", objective: "Atualizar o atendimento quando o contexto do cliente mudar, sem sobrescrever a fotografia anterior.", what: "Novo planejamento do tipo Revisão, Replanejamento ou Simulação.", why: "Mantém a evolução do cliente e base para nova proposta.", who: "Consultor responsável pela carteira.", when: "Em revisões periódicas, mudança de necessidade ou nova decisão comercial.", where: "Carteira, Planejamentos e dashboard do cliente.", how: "Inicie revisão pela Carteira ou crie novo planejamento e repita o fluxo.", howMuch: "Não se aplica diretamente.", steps: ["Abra cliente na Carteira ou Planejamentos.", "Escolha Iniciar revisão ou crie planejamento adequado.", "Registre nova fotografia e novas versões quando necessário.", "Mantenha histórico anterior em consulta."], done: "O novo contexto possui registros próprios e o histórico anterior continua preservado.", next: "Repita Diagnóstico, Análise, Proposta e apresentação conforme a necessidade.", errors: ["Editar diagnóstico ou proposta histórica.", "Confundir ajuste leve de solução com revisão completa."], keywords: ["revisão", "replanejamento", "simulação", "histórico", "nova proposta"], href: "/planejamentos", button: "Iniciar revisão" }),
  entry({ id: "configuracoes", number: "A2", category: "Rotina de apoio", name: "Configurações e whitelabel", objective: "Manter identidade institucional usada pelo workspace e documentos.", what: "Nome da corretora, logo, cores e contatos institucionais.", why: "Aplica identidade correta à navegação e relatórios.", who: "Administrador da corretora.", when: "No primeiro acesso ou mudança institucional.", where: "Menu Configurações.", how: "Preencha ou atualize dados, envie logo quando aplicável e salve.", howMuch: "Não se aplica diretamente.", steps: ["Abra Configurações.", "Atualize nome, logo, cores e contatos.", "Salve e confira aplicação visual."], done: "A identidade está salva e refletida onde o sistema a utiliza.", next: "Continue pelo Dashboard ou módulo de atendimento.", errors: ["Assumir seguradora fixa como identidade do sistema.", "Esperar mudança de relatório histórico já gerado."], keywords: ["logo", "cores", "corretora", "contatos", "marca"], href: "/configuracoes", button: "Ir para Configurações" }),
  entry({ id: "demo", number: "A3", category: "Rotina de apoio", name: "Modo demonstração", objective: "Apresentar o produto com dados fictícios e um caso de referência reinicializável.", what: "Ambiente isolado com o caso fictício Rafael, histórico comercial e contexto novo para Metis.", why: "Facilita demonstração sem misturar dados reais e alterações de visitantes.", who: "Apresentador ou consultor em ambiente de demonstração.", when: "Em Preview configurado como demonstração.", where: "Identificado no cabeçalho como Ambiente de demonstração.", how: "Explore Rafael e use Reiniciar demonstração para restaurar a origem da sessão.", howMuch: "Não se aplica diretamente.", steps: ["Confirme o aviso Ambiente de demonstração.", "Use Rafael como referência para cliente, proposta, carteira, relatórios e Metis.", "Ao terminar, escolha Reiniciar demonstração e confirme."], done: "A sessão voltou ao seed de demonstração e alterações temporárias foram descartadas.", next: "Retome a apresentação pelo Dashboard ou pelo cliente Rafael.", errors: ["Tratar dado demonstrativo como cliente real.", "Reiniciar sem avisar que mudanças da sessão serão apagadas."], keywords: ["rafael", "seed", "reiniciar", "fictício", "ambiente demo"] }),
  entry({ id: "backup", number: "A4", category: "Rotina de apoio", name: "Backup e dados", objective: "Exportar ou restaurar a base local usando apenas os recursos disponíveis no MVP.", what: "Exportação e restauração de backup JSON da base local.", why: "Protege dados antes de trocar navegador, equipamento ou realizar restauração.", who: "Administrador ou responsável pelos dados da corretora.", when: "Antes de mudanças relevantes e em rotina definida pela corretora.", where: "Menu Backup e Dados.", how: "Exporte o arquivo, armazene em local seguro e confirme o arquivo antes de restaurar.", howMuch: "Não se aplica diretamente.", steps: ["Abra Backup e Dados.", "Exporte o backup JSON e guarde em local seguro.", "Quando necessário, selecione arquivo para restauração e confirme.", "Após restaurar, confira os registros principais."], done: "O backup foi gerado ou a restauração terminou e os dados foram conferidos.", next: "Continue a operação. Recursos Cloud não fazem parte desta rotina do MVP.", errors: ["Usar backup como banco operacional diário.", "Restaurar sem conferir o arquivo.", "Supor sincronização automática entre computadores."], keywords: ["json", "restaurar", "exportar", "local", "navegador"], href: "/backup", button: "Ir para Backup e Dados" }),
];

const faqs = [
  ["Quando criar novo planejamento?", "Quando mudar a fotografia, o contexto ou a necessidade do cliente. Ajustes de solução dentro do mesmo contexto podem ocorrer em nova versão da proposta."],
  ["Quando duplicar proposta?", "Quando precisar comparar ou alterar uma solução sem sobrescrever versão apresentada, aceita ou histórica."],
  ["Posso editar uma proposta apresentada?", "Não. Crie uma nova versão a partir dela quando houver alteração relevante."],
  ["Quando um cliente entra na Carteira?", "Automaticamente após fechamento ou aceite de proposta válida. Não existe cadastro paralelo de contrato na Carteira."],
  ["Como funciona a Metis?", "Ela apoia com análise de diagnóstico, revisão de proposta e perguntas. O resultado exige revisão profissional e não altera dados."],
  ["O que acontece ao reabrir um diagnóstico?", "A reabertura permite atualização no contexto disponível. Não a use para apagar ou substituir fotografia de revisão histórica."],
  ["Relatório atual e snapshot são iguais?", "Não. O snapshot preserva documento no momento da geração. Alterações posteriores não devem mudar esse histórico."],
];

const fiveW2H = (item: Entry) => [["O quê", item.what], ["Por quê", item.why], ["Quem", item.who], ["Quando", item.when], ["Onde", item.where], ["Como", item.how], ["Quanto", item.howMuch]];
const searchable = (item: Entry) => [item.name, item.objective, item.what, item.why, item.who, item.when, item.where, item.how, item.howMuch, item.done, item.next, ...item.steps, ...item.errors, ...item.keywords].join(" ").toLocaleLowerCase("pt-BR");

export function HelpGuide() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState<"Tudo" | Category>("Tudo");
  const normalized = query.trim().toLocaleLowerCase("pt-BR");
  const filtered = useMemo(() => entries.filter((item) => (category === "Tudo" || item.category === category) && (!normalized || searchable(item).includes(normalized))), [category, normalized]);

  return <div className="page help-page">
    <section className="hero help-hero"><div><p className="eyebrow">GUIA OPERACIONAL</p><h2>Guia Operacional do 7Protect</h2><p>Do primeiro contato ao acompanhamento da proteção financeira do cliente. Use como orientação de trabalho, não como workflow rígido quando houver exceções.</p></div></section>
    <section className="card help-flow"><p className="eyebrow">FLUXO PRINCIPAL</p><h3>Lead <span>↓</span> Kanban <span>↓</span> Cliente <span>↓</span> Diagnóstico <span>↓</span> Planejamento <span>↓</span> Análise profissional <span>↓</span> Proposta <span>↓</span> Metis <span>↓</span> Apresentação <span>↓</span> Fechamento <span>↓</span> Carteira <span>↓</span> Relatórios <span>↓</span> Revisão</h3><p>Catálogo, Configurações, Modo demonstração e Backup e Dados são rotinas de apoio. Elas não precisam ocorrer em todo atendimento.</p></section>
    <section className="card help-explorer" aria-labelledby="guide-explorer-title"><div className="help-explorer-heading"><div><p className="eyebrow">LOCALIZE UMA ETAPA</p><h3 id="guide-explorer-title">Guia por contexto</h3></div><p>{filtered.length} {filtered.length === 1 ? "item encontrado" : "itens encontrados"}</p></div><label className="help-search"><span>Buscar no guia</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ex.: proposta, Metis, carteira ou revisão" type="search" /></label><div className="help-filters" aria-label="Filtrar guia"><button type="button" className={category === "Tudo" ? "active" : ""} onClick={() => setCategory("Tudo")}>Tudo</button><button type="button" className={category === "Fluxo principal" ? "active" : ""} onClick={() => setCategory("Fluxo principal")}>Fluxo principal</button><button type="button" className={category === "Rotina de apoio" ? "active" : ""} onClick={() => setCategory("Rotina de apoio")}>Rotinas de apoio</button></div><nav className="help-index" aria-label="Índice da ajuda">{filtered.map((item) => <a href={"#" + item.id} key={item.id}>{item.number} · {item.name}</a>)}</nav></section>
    <section className="help-entries" aria-label="Conteúdo do guia">{filtered.map((item) => <details className="card help-entry" id={item.id} key={item.id} open={item.id === "lead" && !normalized && category === "Tudo"}><summary><span className="help-entry-number" aria-hidden="true">{item.number}</span><span className="help-entry-title"><small>{item.category}</small><strong>{item.name}</strong><em>{item.objective}</em></span><span className="help-entry-toggle" aria-hidden="true">⌄</span></summary><div className="help-entry-body"><section><h4>Objetivo</h4><p>{item.objective}</p></section><section><h4>5W2H resumido</h4><dl className="fivew2h">{fiveW2H(item).map(([term, description]) => <div key={term}><dt>{term}</dt><dd>{description}</dd></div>)}</dl></section><section><h4>Como executar</h4><ol>{item.steps.map((step) => <li key={step}>{step}</li>)}</ol></section><div className="help-outcome-grid"><section><h4>Quando considerar concluído</h4><p>{item.done}</p></section><section><h4>O que acontece depois</h4><p>{item.next}</p></section></div><section><h4>Erros comuns</h4><ul>{item.errors.map((error) => <li key={error}>{error}</li>)}</ul></section>{item.href && item.button ? <Link href={item.href} className="button secondary">{item.button}</Link> : <p className="help-context-note"><strong>Uso contextual:</strong> acesse Metis pelo dashboard do cliente ou pela proposta. Não há atalho genérico sem cliente e contexto.</p>}</div></details>)}{!filtered.length ? <section className="empty"><h2>Nenhuma etapa encontrada</h2><p>Tente uma palavra como proposta, diagnóstico, Metis, carteira ou revisão.</p><button className="button secondary" type="button" onClick={() => { setQuery(""); setCategory("Tudo"); }}>Limpar busca</button></section> : null}</section>
    <section className="card help-faq"><p className="eyebrow">FAQ COMPLEMENTAR</p><h3>Dúvidas frequentes</h3><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
  </div>;
}
