"use client";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { operationalOverview, markCommercialNotificationRead, transitionCommercialActivity, prepareOperationalDemo } from "@/application/operational-service";
import { ACTIVITY_LABEL } from "@/application/commercial-service";
import type { ActivityCycleEvent, CommercialActivity } from "@/domains/core/entities";
import { useFoundation } from "./foundation-provider";
import { CrudDrawer } from "./crud-drawer";
import { SafeForm } from "./commercial-form";

type Overview = Awaited<ReturnType<typeof operationalOverview>>;
const date = (value?: string) => value ? new Date(value).toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo" }) : "Sem data";
const severity = { info: "Informação", attention: "Atenção", critical: "Crítico" };
function useOperationalData() {
  const { ready, settings } = useFoundation(); const [data, setData] = useState<Overview | null>(null); const [error, setError] = useState("");
  const reload = useCallback(async () => { try { setError(""); setData(await operationalOverview()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar a Agenda."); } }, []);
  useEffect(() => { if (ready && settings) { const timer = window.setTimeout(() => { void reload(); }, 0); return () => window.clearTimeout(timer); } }, [ready, settings, reload]);
  return { data, error, reload };
}
export function AttentionCenter({ compact = false }: { compact?: boolean }) {
  const { data, error, reload } = useOperationalData();
  if (!data) return <section className="card attention-center"><h3>Precisa da sua atenção</h3><p>{error || "Carregando prioridades..."}</p></section>;
  return <AttentionList data={data} reload={reload} compact={compact} />;
}
function AttentionList({ data, reload, compact = false }: { data: Overview; reload: () => Promise<void>; compact?: boolean }) {
  const notifications = new Map(data.notifications.map((item) => [item.causeKey, item]));
  return <section className="card attention-center"><div className="attention-heading"><div><h3>Precisa da sua atenção</h3><p>{data.attention.length} pontos para acompanhar</p></div>{compact ? <Link className="button secondary" href="/agenda">Abrir Agenda</Link> : <button className="button secondary" onClick={() => void reload()}>Atualizar</button>}</div><div className="attention-items">{(compact ? data.attention.slice(0, 5) : data.attention).map((cause) => { const notice = notifications.get(cause.causeKey); return <article key={cause.causeKey} className={`attention-item severity-${cause.severity}`}><div><b>{cause.title}</b><span>{severity[cause.severity!]}</span><p>{cause.message}</p>{cause.dueAt ? <small>{date(cause.dueAt)}</small> : null}</div><div className="commercial-actions">{notice?.status === "unread" ? <button className="button secondary" onClick={async () => { await markCommercialNotificationRead(notice.id); await reload(); }}>Marcar lida</button> : null}<Link className="button secondary" href={cause.href}>{cause.action}</Link>{cause.contactId ? <Link className="button secondary" href={`/hot40?contact=${cause.contactId}`}>Abrir contato</Link> : null}</div></article>; })}{!data.attention.length ? <p>Nenhuma prioridade pendente agora.</p> : null}</div></section>;
}
export function OperationalWorkspace() {
  const { data, error, reload } = useOperationalData(); const { demo } = useFoundation(); const [tab, setTab] = useState<"today" | "overdue" | "upcoming" | "noNext">("today"); const [demoError, setDemoError] = useState(""); const [preparing, setPreparing] = useState(false);
  const [editing, setEditing] = useState<{ activity: CommercialActivity; action: ActivityCycleEvent["action"]; commandKey: string } | null>(null);
  const opened = useRef(false);
  useEffect(() => { const id = new URLSearchParams(window.location.search).get("activity"); if (id && data && !opened.current) { opened.current = true; const activity = data.data.activities.find((item) => item.id === id && item.status === "planned"); if (activity) { const timer = window.setTimeout(() => { setTab("overdue"); setEditing({ activity, action: "complete", commandKey: crypto.randomUUID() }); }, 0); return () => window.clearTimeout(timer); } } }, [data]);
  if (!data) return <div className="page commercial-page"><p>{error || "Carregando Agenda..."}</p></div>;
  const entries = tab === "today" ? data.agenda.today : tab === "overdue" ? data.agenda.overdue : data.agenda.upcoming;
  const openAction = (activity: CommercialActivity, action: ActivityCycleEvent["action"]) => setEditing({ activity, action, commandKey: crypto.randomUUID() });
  return <div className="page commercial-page operational-page"><section className="hero"><div><p className="eyebrow">DOMÍNIO COMERCIAL V2</p><h2>Agenda operacional</h2><p>Atividades planejadas, prazos e próximos passos.</p></div>{demo ? <button className="button secondary" disabled={preparing} onClick={async () => { try { setPreparing(true); setDemoError(""); await prepareOperationalDemo(); await reload(); } catch (cause) { setDemoError(cause instanceof Error ? cause.message : "Falha ao preparar cenário."); } finally { setPreparing(false); } }}>Preparar cenário de validação</button> : null}</section>{error || demoError ? <p role="alert">{error || demoError}</p> : null}
    <nav className="segmented indicator-tabs" aria-label="Faixas da Agenda">{([["today", "Hoje", data.agenda.today.length], ["overdue", "Atrasadas", data.agenda.overdue.length], ["upcoming", "Próximas", data.agenda.upcoming.length], ["noNext", "Sem próxima ação", data.agenda.noNext.length]] as const).map(([key, label, count]) => <button key={key} className={tab === key ? "active" : ""} onClick={() => setTab(key)}>{label} ({count})</button>)}</nav>
    <section className="card operational-list">{tab === "noNext" ? data.agenda.noNext.map(({ member, contact }) => <article key={member.id} className="operational-row"><div><b>{contact.fullName}</b><p>HOT40 sem atividade futura planejada. Etapa: {member.stage || "ab_phone"}.</p></div><Link className="button secondary" href={`/hot40?contact=${contact.id}&action=new`}>Planejar atividade</Link></article>) : entries.map(({ activity, contact, stage, overdueMs }) => <article className="operational-row" key={activity.id}><div><b>{contact.fullName}</b><p>{ACTIVITY_LABEL[activity.type]} · {date(activity.scheduledAt)} · HOT40: {stage || "fora da carteira"}</p>{overdueMs > 0 ? <small>Atraso: {Math.floor(overdueMs / 86400000)} dias, {Math.floor(overdueMs / 3600000) % 24} horas</small> : null}</div><div className="commercial-actions"><button className="button secondary" onClick={() => openAction(activity, "complete")}>Registrar realização</button><button className="button secondary" onClick={() => openAction(activity, "reschedule")}>Reagendar</button><button className="button secondary" onClick={() => openAction(activity, "cancel")}>Cancelar</button><Link className="button secondary" href={`/hot40?contact=${contact.id}`}>Abrir contato</Link></div></article>)}{tab === "noNext" ? !data.agenda.noNext.length && <p>Todos os contatos HOT40 têm próxima ação.</p> : !entries.length && <p>Nenhuma atividade nesta faixa.</p>}</section>
    <AttentionList data={data} reload={reload} />
    <details className="card notification-history"><summary>Histórico de notificações ({data.notifications.length})</summary><div>{[...data.notifications].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map((item) => <article key={item.id}><b>{item.title}</b><span>{item.status === "unread" ? "Não lida" : item.status === "read" ? "Lida" : "Resolvida"}</span><p>{item.message}</p><small>Criada: {date(item.createdAt)}{item.readAt ? ` · Lida: ${date(item.readAt)}` : ""}{item.resolvedAt ? ` · Resolvida: ${date(item.resolvedAt)}` : ""}</small></article>)}</div></details>
    {editing ? <CrudDrawer title={editing.action === "complete" ? "Registrar realização" : editing.action === "cancel" ? "Cancelar atividade" : "Reagendar atividade"} description={`${ACTIVITY_LABEL[editing.activity.type]} · planejada para ${date(editing.activity.scheduledAt)}. O mesmo registro será atualizado.`} onClose={() => setEditing(null)}><SafeForm action={async (form) => { await transitionCommercialActivity({ activityId: editing.activity.id, expectedVersion: editing.activity.version, commandKey: editing.commandKey, action: editing.action, at: editing.action !== "cancel" ? String(form.get("at")) : undefined, reason: String(form.get("reason") || "") }); setEditing(null); await reload(); }}><section className="crud-form-section"><div className="crud-form-grid">{editing.action !== "cancel" ? <label className="crud-field full">{editing.action === "complete" ? "Data realizada" : "Nova data agendada"}<input type="datetime-local" name="at" required /></label> : null}{editing.action !== "complete" ? <label className="crud-field full">Motivo<textarea name="reason" maxLength={2000} required /></label> : null}</div></section><footer className="crud-actions"><button type="button" className="button secondary" onClick={() => setEditing(null)}>Voltar</button><button className="button primary">Confirmar</button></footer></SafeForm></CrudDrawer> : null}
  </div>;
}
