"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState } from "react";
import { addCatalogItem, completeDiagnostic, createPlanningCycle, createProposalVersion, ensurePlanningDemo, listPlanningClients, planningWorkspace, presentProposal, reopenDiagnostic, saveBrokerAnalysis, saveDiagnostic, closePlanning } from "@/application/planning-service";
import type { BrokerAnalysis, Client, Diagnostic, PlanningCycle, ProposalVersion } from "@/domains/core/entities";

const STEPS = [["identification", "Identificação"], ["family", "Família e dependentes"], ["workIncome", "Trabalho e renda"], ["expenses", "Despesas"], ["assets", "Patrimônio"], ["reserves", "Reservas e investimentos"], ["pensions", "Previdência"], ["debts", "Dívidas e compromissos"], ["existingInsurance", "Seguros existentes"], ["health", "Saúde"], ["goals", "Objetivos e prioridades"], ["review", "Revisão final"]] as const;
const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

export function PlanningWorkspace({ section = "diagnostics" }: { section?: "diagnostics" | "planning" | "proposals" }) {
  const [clients, setClients] = useState<Client[]>([]); const [clientId, setClientId] = useState(""); const [cycleId, setCycleId] = useState(""); const [workspace, setWorkspace] = useState<Awaited<ReturnType<typeof planningWorkspace>> | null>(null); const [step, setStep] = useState(0); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const refresh = async (selectedClient = clientId, selectedCycle = cycleId) => { if (!selectedClient) return; const next = await planningWorkspace(selectedClient, selectedCycle || undefined); setWorkspace(next); setCycleId(next.cycle.id); };
  useEffect(() => { void (async () => { const demoClient = await ensurePlanningDemo(); const rows = await listPlanningClients(); setClients(rows); const selected = demoClient ?? rows[0]?.id ?? ""; setClientId(selected); if (selected) await refresh(selected); })(); }, []);
  useEffect(() => { if (clientId) void refresh(clientId, ""); }, [clientId]);
  const createCycle = async () => { if (!clientId) return; const cycle = await createPlanningCycle(clientId); setCycleId(cycle.id); await refresh(clientId, cycle.id); setNotice("Novo ciclo de planejamento criado."); };
  const saveDiagnosis = async (data: Record<string, unknown>) => { if (!workspace) return; setBusy(true); try { await saveDiagnostic(workspace.diagnostic, data); await refresh(); setNotice("Rascunho salvo automaticamente no dispositivo."); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível salvar o diagnóstico."); } finally { setBusy(false); } };
  const complete = async () => { if (!workspace) return; setBusy(true); try { await completeDiagnostic(workspace.diagnostic); await refresh(); setNotice("Diagnóstico concluído. A tarefa foi criada em A calcular."); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível concluir."); } finally { setBusy(false); } };
  const saveAnalysis = async (form: FormData) => { if (!workspace) return; await saveBrokerAnalysis({ id: workspace.analysis?.id, clientId: workspace.cycle.clientId, planningCycleId: workspace.cycle.id, summary: String(form.get("summary")), priorities: String(form.get("priorities")), hypotheses: String(form.get("hypotheses")), estimatedNeed: Number(form.get("estimatedNeed")) || undefined, timeframe: String(form.get("timeframe")), calculationNotes: String(form.get("calculationNotes")), recommendations: String(form.get("recommendations")), pendingQuestions: String(form.get("pendingQuestions")), internalNotes: String(form.get("internalNotes")) }); await refresh(); setNotice("Análise profissional salva separadamente do diagnóstico."); };
  const addVersion = async () => { if (!workspace) return; await createProposalVersion(workspace.cycle, workspace.diagnostic, workspace.analysis, workspace.proposals.length ? "Revisão da proposta" : "Primeira versão"); await refresh(); setNotice("Nova versão criada. Versões apresentadas permanecem preservadas."); };
  const present = async (proposal: ProposalVersion) => { await presentProposal(proposal); await refresh(); setNotice(`Proposta v${proposal.number} marcada como apresentada.`); };
  const close = async (proposal: ProposalVersion) => { if (!workspace) return; await closePlanning(workspace.cycle, proposal, new Date(Date.now() + 365 * 86400000).toISOString().slice(0, 10)); await refresh(); setNotice(`Fechamento registrado para a proposta v${proposal.number}.`); };
  const addCatalog = async (form: FormData) => { const kind = String(form.get("kind")) as "insurer" | "product" | "coverageType"; await addCatalogItem(kind, String(form.get("name")), String(form.get("insurerId")) || undefined); await refresh(); setNotice("Catálogo atualizado."); };
  return <div className="page planning-page"><section className="hero"><div><p className="eyebrow">PLANEJAMENTO DE PROTEÇÃO</p><h2>{section === "diagnostics" ? "Diagnósticos" : section === "planning" ? "Planejamento da corretora" : "Propostas versionadas"}</h2><p>Dados declarados, análise da corretora, cálculos e propostas mantidos em registros distintos.</p></div></section><section className="card planning-toolbar"><label>Cliente<select value={clientId} onChange={(event) => setClientId(event.target.value)}>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label>Ciclo<select value={cycleId} onChange={(event) => { setCycleId(event.target.value); void refresh(clientId, event.target.value); }}>{workspace?.cycles.map((cycle) => <option key={cycle.id} value={cycle.id}>{cycle.name}</option>)}</select></label><button className="button secondary" onClick={() => void createCycle()}>Novo ciclo</button></section>{notice ? <p className="notice">{notice}</p> : null}{workspace ? <>{section === "diagnostics" ? <DiagnosticEditor diagnostic={workspace.diagnostic} step={step} setStep={setStep} busy={busy} save={saveDiagnosis} complete={complete} reopen={async () => { await reopenDiagnostic(workspace.diagnostic); await refresh(); }} /> : null}{section === "planning" ? <AnalysisEditor analysis={workspace.analysis} cycle={workspace.cycle} save={saveAnalysis} /> : null}{section === "proposals" ? <ProposalEditor workspace={workspace} addVersion={addVersion} present={present} close={close} addCatalog={addCatalog} /> : null}<section className="card planning-history"><p className="eyebrow">HISTÓRICO DO CICLO</p><h3>{workspace.cycle.status === "closed" ? "Fechamento registrado" : "Ciclo em andamento"}</h3><p>Diagnóstico: {workspace.diagnostic.status}. Propostas: {workspace.proposals.length}. {workspace.closing ? `Versão aceita: v${workspace.proposals.find((item) => item.proposal.id === workspace.closing?.proposalVersionId)?.proposal.number ?? ""}.` : "Nenhuma versão aceita ainda."}</p></section></> : <p className="notice">Carregando dados locais...</p>}</div>;
}

function DiagnosticEditor({ diagnostic, step, setStep, busy, save, complete, reopen }: { diagnostic: Diagnostic; step: number; setStep: (value: number) => void; busy: boolean; save: (data: Record<string, unknown>) => Promise<void>; complete: () => Promise<void>; reopen: () => Promise<void> }) { const [data, setData] = useState(diagnostic.declaredData); useEffect(() => setData(diagnostic.declaredData), [diagnostic.id, diagnostic.updatedAt]); const [key, title] = STEPS[step]; const update = (field: string, value: string) => { const next = { ...data, [field]: value }; setData(next); window.clearTimeout((update as unknown as { timer?: number }).timer); (update as unknown as { timer?: number }).timer = window.setTimeout(() => void save(next), 600); }; const finished = diagnostic.status === "completed"; return <section className="card diagnostic-editor"><div className="stepper">{STEPS.map(([, label], index) => <button type="button" key={label} className={index === step ? "active" : ""} onClick={() => setStep(index)}>{index + 1}</button>)}</div><p className="eyebrow">ETAPA {step + 1} DE {STEPS.length}</p><h3>{title}</h3><textarea disabled={finished} value={String(data[key] ?? "")} onChange={(event) => update(key, event.target.value)} placeholder={`Registre os dados declarados pelo cliente sobre ${title.toLowerCase()}.`} /><div className="two"><label>Renda familiar mensal<input disabled={finished} type="number" value={String(data.familyIncome ?? "")} onChange={(event) => update("familyIncome", event.target.value)} /></label><label>Despesa familiar mensal<input disabled={finished} type="number" value={String(data.monthlyExpense ?? "")} onChange={(event) => update("monthlyExpense", event.target.value)} /></label></div><div className="planning-actions"><button className="button secondary" disabled={step === 0} onClick={() => setStep(step - 1)}>Anterior</button><button className="button secondary" disabled={step === STEPS.length - 1} onClick={() => setStep(step + 1)}>Próxima</button>{finished ? <button className="button secondary" onClick={() => void reopen()}>Reabrir diagnóstico</button> : <button className="button primary" disabled={busy} onClick={() => void complete()}>{busy ? "Salvando..." : "Concluir diagnóstico"}</button>}</div></section> }
function AnalysisEditor({ analysis, cycle, save }: { analysis: BrokerAnalysis | null; cycle: PlanningCycle; save: (form: FormData) => Promise<void> }) { return <form className="card planning-form" action={async (form) => { await save(form); }}><p className="eyebrow">USO EXCLUSIVO DA CORRETORA</p><h3>Análise profissional</h3><textarea name="summary" defaultValue={analysis?.summary} placeholder="Resumo do caso" /><textarea name="priorities" defaultValue={analysis?.priorities} placeholder="Prioridades identificadas" /><textarea name="hypotheses" defaultValue={analysis?.hypotheses} placeholder="Hipóteses de planejamento" /><div className="two"><label>Necessidade estimada<input name="estimatedNeed" type="number" defaultValue={analysis?.estimatedNeed} /></label><label>Prazo considerado<input name="timeframe" defaultValue={analysis?.timeframe} placeholder="Ex.: 15 anos" /></label></div><textarea name="calculationNotes" defaultValue={analysis?.calculationNotes} placeholder="Observações de cálculo" /><textarea name="recommendations" defaultValue={analysis?.recommendations} placeholder="Recomendações a validar" /><textarea name="pendingQuestions" defaultValue={analysis?.pendingQuestions} placeholder="Perguntas pendentes" /><textarea name="internalNotes" defaultValue={analysis?.internalNotes} placeholder="Notas internas, não exibidas ao cliente" /><button className="button primary">Salvar análise</button></form> }
function ProposalEditor({ workspace, addVersion, present, close, addCatalog }: { workspace: Awaited<ReturnType<typeof planningWorkspace>>; addVersion: () => Promise<void>; present: (proposal: ProposalVersion) => Promise<void>; close: (proposal: ProposalVersion) => Promise<void>; addCatalog: (form: FormData) => Promise<void> }) { return <section className="proposal-area"><section className="card"><p className="eyebrow">CATÁLOGO CONFIGURÁVEL</p><h3>{workspace.catalog.insurers.map((item) => item.name).join(" · ") || "Sem seguradoras cadastradas"}</h3><p>Seguradoras, produtos e tipos de cobertura são dados configuráveis. Nenhuma marca é obrigatória no produto.</p><form className="catalog-form" action={async (form) => { await addCatalog(form); }}><select name="kind"><option value="insurer">Seguradora</option><option value="product">Produto</option><option value="coverageType">Tipo de cobertura</option></select><select name="insurerId"><option value="">Seguradora do produto</option>{workspace.catalog.insurers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input name="name" placeholder="Nome do item" required /><button className="button secondary">Adicionar ao catálogo</button></form><button className="button primary" onClick={() => void addVersion()}>Criar nova versão</button></section>{workspace.proposals.map(({ proposal, coverages }) => <article className="card proposal-card" key={proposal.id}><p className="eyebrow">VERSÃO {proposal.number} · {proposal.status}</p><h3>{money(proposal.totalMonthly)}/mês · capital protegido {money(proposal.totalProtectedCapital)}</h3><p>{proposal.revisionReason ?? "Sem motivo registrado"}. Comprometimento de renda: {proposal.incomeCommitment}%.</p>{coverages.map((coverage) => <p key={coverage.id}>{coverage.label}: {money(coverage.insuredCapital ?? 0)} · {money(coverage.monthlyPremium ?? 0)}/mês</p>)}<div className="planning-actions">{proposal.status === "draft" ? <button className="button secondary" onClick={() => void present(proposal)}>Marcar apresentada</button> : null}{proposal.status === "presented" ? <button className="button primary" onClick={() => void close(proposal)}>Registrar fechamento</button> : null}</div></article>)}</section> }
