"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { addCatalogItem, closePlanning, completeDiagnostic, createPlanningCycle, createProposalVersion, ensurePlanningDemo, listPlanningClients, planningWorkspace, presentProposal, reopenDiagnostic, requestProposalRevision, saveBrokerAnalysis, saveDiagnostic } from "@/application/planning-service";
import { generateDiagnosticPdf, type DiagnosticPdfMode } from "@/application/diagnostic-pdf-service";
import type { BrokerAnalysis, Client, Diagnostic, PlanningCycle, PlanningEvent, PlanningType, ProposalVersion } from "@/domains/core/entities";

const STEPS = [["identification", "Identificação"], ["family", "Família e dependentes"], ["workIncome", "Trabalho e renda"], ["expenses", "Despesas"], ["assets", "Patrimônio"], ["reserves", "Reservas e investimentos"], ["pensions", "Previdência"], ["debts", "Dívidas e compromissos"], ["existingInsurance", "Seguros existentes"], ["health", "Saúde"], ["goals", "Objetivos e prioridades"], ["review", "Revisão completa"]] as const;
const TYPE_LABEL: Record<PlanningType, string> = { initial: "Inicial", review: "Revisão", replanning: "Replanejamento", simulation: "Simulação" };
const money = (value: unknown) => typeof value === "number" && value > 0 ? value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" }) : "Não informado";
const date = (value: string) => new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" }).format(new Date(value.slice(0, 10) + "T00:00:00Z"));
const dateTime = (value: string) => new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value));
type Workspace = Awaited<ReturnType<typeof planningWorkspace>>;
type PopulatedWorkspace = Workspace & { client: Client; cycle: PlanningCycle; diagnostic: Diagnostic };
type PlanningForm = { name: string; referenceDate: string; type: PlanningType; observation: string };
const emptyForm = (): PlanningForm => ({ name: "", referenceDate: new Date().toISOString().slice(0, 10), type: "initial", observation: "" });

export function PlanningWorkspace({ section = "diagnostics" }: { section?: "diagnostics" | "planning" | "proposals" }) {
  const [clients, setClients] = useState<Client[]>([]); const [clientId, setClientId] = useState(""); const [planningId, setPlanningId] = useState(""); const [workspace, setWorkspace] = useState<Workspace | null>(null); const [step, setStep] = useState(0); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const [showCreate, setShowCreate] = useState(false); const [confirmNew, setConfirmNew] = useState(false); const [form, setForm] = useState<PlanningForm>(emptyForm()); const [viewDiagnosis, setViewDiagnosis] = useState(false);
  const refresh = async (selectedClient = clientId, selectedPlanning = planningId) => { if (!selectedClient) return; const next = await planningWorkspace(selectedClient, selectedPlanning || undefined); setWorkspace(next); setPlanningId(next.cycle?.id ?? ""); };
  useEffect(() => { void (async () => { const demoClient = await ensurePlanningDemo(); const rows = await listPlanningClients(); setClients(rows); const selected = demoClient ?? rows[0]?.id ?? ""; setClientId(selected); if (selected) await refresh(selected); })(); }, []);
  useEffect(() => { if (clientId) void refresh(clientId, ""); }, [clientId]);
  const openCreate = () => { setForm(emptyForm()); setConfirmNew(false); setShowCreate(true); };
  const createPlanning = async () => { if (!clientId) return; setBusy(true); try { const planning = await createPlanningCycle({ clientId, ...form }); setShowCreate(false); setConfirmNew(false); setPlanningId(planning.id); await refresh(clientId, planning.id); setNotice("Planejamento criado e pronto para o diagnóstico."); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível criar o planejamento."); } finally { setBusy(false); } };
  const submitPlanning = () => { const ongoing = workspace?.cycles.find((item) => item.status !== "closed"); if (ongoing && !confirmNew) { setConfirmNew(true); return; } void createPlanning(); };
  const continuePlanning = () => { const ongoing = workspace?.cycles.find((item) => item.status !== "closed"); if (!ongoing) return; setShowCreate(false); setConfirmNew(false); setPlanningId(ongoing.id); void refresh(clientId, ongoing.id); setNotice("Continuando " + ongoing.name + "."); };
  const saveDiagnosis = async (data: Record<string, unknown>) => { if (!workspace?.diagnostic) return; setBusy(true); try { await saveDiagnostic(workspace.diagnostic, data); await refresh(); setNotice("Rascunho salvo automaticamente neste dispositivo."); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível salvar o diagnóstico."); } finally { setBusy(false); } };
  const complete = async () => { if (!workspace?.diagnostic) return; setBusy(true); try { await completeDiagnostic(workspace.diagnostic); await refresh(); setNotice("Diagnóstico concluído. A tarefa foi criada em A calcular."); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível concluir."); } finally { setBusy(false); } };
  const saveAnalysis = async (data: FormData) => { if (!workspace?.cycle) return; try { await saveBrokerAnalysis({ id: workspace.analysis?.id, clientId: workspace.cycle.clientId, planningCycleId: workspace.cycle.id, summary: String(data.get("summary")), priorities: String(data.get("priorities")), hypotheses: String(data.get("hypotheses")), estimatedNeed: Number(data.get("estimatedNeed")) || undefined, timeframe: String(data.get("timeframe")), calculationNotes: String(data.get("calculationNotes")), recommendations: String(data.get("recommendations")), pendingQuestions: String(data.get("pendingQuestions")), internalNotes: String(data.get("internalNotes")) }); await refresh(); setNotice("Análise profissional atualizada."); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível salvar a análise."); } };
  const addVersion = async () => { if (!workspace?.cycle || !workspace.diagnostic) return; await createProposalVersion(workspace.cycle, workspace.diagnostic, workspace.analysis, workspace.proposals.length ? "Revisão da proposta" : "Primeira versão"); await refresh(); setNotice("Nova versão criada. Versões apresentadas permanecem preservadas."); };
  const present = async (proposal: ProposalVersion) => { await presentProposal(proposal); await refresh(); setNotice("Proposta v" + proposal.number + " marcada como apresentada."); };
  const requestRevision = async (proposal: ProposalVersion) => { if (!workspace?.cycle) return; await requestProposalRevision(workspace.cycle, proposal); await refresh(); setNotice("Pedido de revisão da proposta v" + proposal.number + " registrado."); };
  const close = async (proposal: ProposalVersion) => { if (!workspace?.cycle) return; await closePlanning(workspace.cycle, proposal, new Date(Date.now() + 365 * 86400000).toISOString().slice(0, 10)); await refresh(); setNotice("Fechamento registrado para a proposta v" + proposal.number + "."); };
  const addCatalog = async (data: FormData) => { const kind = String(data.get("kind")) as "insurer" | "product" | "coverageType"; await addCatalogItem(kind, String(data.get("name")), String(data.get("insurerId")) || undefined); await refresh(); setNotice("Catálogo atualizado."); };
  const populated = workspace?.cycle && workspace.diagnostic && workspace.client ? workspace as PopulatedWorkspace : null;
  return <div className="page planning-page">
    <section className="hero"><div><p className="eyebrow">PLANEJAMENTO DE PROTEÇÃO</p><h2>{section === "diagnostics" ? "Diagnósticos" : section === "planning" ? "Planejamento da corretora" : "Propostas versionadas"}</h2><p>Dados declarados, análise da corretora, cálculos e propostas mantidos em registros distintos.</p></div></section>
    <section className="card planning-toolbar"><label>Cliente<select value={clientId} onChange={(event) => setClientId(event.target.value)}>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label>Planejamento<select value={planningId} onChange={(event) => { setPlanningId(event.target.value); void refresh(clientId, event.target.value); }} disabled={!workspace?.cycles.length}><option value="">Selecione um planejamento</option>{workspace?.cycles.map((item) => <option key={item.id} value={item.id}>{item.name + " · " + TYPE_LABEL[item.type ?? "initial"] + " · " + date(item.referenceDate ?? item.startedAt) + " · " + item.status}</option>)}</select></label><button className="button secondary" onClick={openCreate}>Novo planejamento</button><Link className="context-help" href="/ajuda#planejamento" aria-label="Ajuda sobre planejamentos">?</Link></section>
    {notice ? <p className="notice" role="status">{notice}</p> : null}
    {populated ? <><PlanningSummary workspace={populated} onView={() => setViewDiagnosis(true)} />{section === "diagnostics" ? <DiagnosticEditor diagnostic={populated.diagnostic} step={step} setStep={setStep} busy={busy} save={saveDiagnosis} complete={complete} reopen={async () => { await reopenDiagnostic(populated.diagnostic); await refresh(); }} onView={() => setViewDiagnosis(true)} /> : null}{section === "planning" ? <AnalysisEditor analysis={populated.analysis} save={saveAnalysis} /> : null}{section === "proposals" ? <ProposalEditor workspace={populated} addVersion={addVersion} present={present} requestRevision={requestRevision} close={close} addCatalog={addCatalog} /> : null}<PlanningTimeline events={populated.events} /></> : <section className="card empty-state"><h3>Nenhum planejamento selecionado</h3><p>Crie um planejamento quando houver uma nova fotografia ou mudança relevante no contexto do cliente.</p><button className="button primary" onClick={openCreate}>Criar planejamento</button></section>}
    {showCreate ? <PlanningModal form={form} setForm={setForm} busy={busy} confirming={confirmNew} onCancel={() => { setShowCreate(false); setConfirmNew(false); }} onSubmit={submitPlanning} onContinue={continuePlanning} onCreate={createPlanning} /> : null}
    {viewDiagnosis && populated ? <DiagnosticView workspace={populated} onClose={() => setViewDiagnosis(false)} onPdf={async (mode) => { setBusy(true); try { await generateDiagnosticPdf({ client: populated.client, planning: populated.cycle, diagnostic: populated.diagnostic, analysis: populated.analysis, mode }); setNotice(mode === "client" ? "PDF para o cliente gerado localmente." : "PDF completo interno gerado localmente."); } catch { setNotice("Não foi possível gerar o PDF."); } finally { setBusy(false); } }} /> : null}
  </div>;
}
function PlanningSummary({ workspace, onView }: { workspace: PopulatedWorkspace; onView: () => void }) { const presented = workspace.proposals.find((item) => item.proposal.status === "presented")?.proposal; const accepted = workspace.proposals.find((item) => item.proposal.status === "accepted")?.proposal; const last = workspace.events[0]; return <section className="card planning-summary"><div><p className="eyebrow">RESUMO DO PLANEJAMENTO</p><h3>{workspace.cycle.name}</h3><p>{TYPE_LABEL[workspace.cycle.type ?? "initial"]} · Referência em {date(workspace.cycle.referenceDate ?? workspace.cycle.startedAt)} · {workspace.cycle.status}.</p></div><button className="button secondary" onClick={onView}>Visualizar diagnóstico</button><dl className="planning-facts"><div><dt>Status do diagnóstico</dt><dd>{workspace.diagnostic.status}</dd></div><div><dt>Propostas</dt><dd>{workspace.proposals.length}</dd></div><div><dt>Versão apresentada</dt><dd>{presented ? "v" + presented.number : "Nenhuma"}</dd></div><div><dt>Versão aceita</dt><dd>{accepted ? "v" + accepted.number : "Nenhuma"}</dd></div><div><dt>Última movimentação</dt><dd>{last ? last.description + " · " + dateTime(last.occurredAt) : "Sem movimentações"}</dd></div></dl></section> }
function PlanningModal({ form, setForm, busy, confirming, onCancel, onSubmit, onContinue, onCreate }: { form: PlanningForm; setForm: (value: PlanningForm) => void; busy: boolean; confirming: boolean; onCancel: () => void; onSubmit: () => void; onContinue: () => void; onCreate: () => void }) { return <div className="modal-backdrop" role="presentation"><section className="card planning-modal" role="dialog" aria-modal="true" aria-labelledby="planning-modal-title"><p className="eyebrow">NOVO PLANEJAMENTO</p><h3 id="planning-modal-title">Contexto da nova fotografia</h3>{confirming ? <><p className="warning">Já existe um planejamento em andamento para este cliente.</p><p>Propostas diferentes do mesmo contexto devem ser versões dentro do planejamento.</p><div className="planning-actions"><button type="button" className="button secondary" onClick={onContinue}>Continuar planejamento atual</button><button type="button" className="button primary" disabled={busy} onClick={onCreate}>Criar novo planejamento</button></div></> : <form onSubmit={(event) => { event.preventDefault(); onSubmit(); }} className="planning-form"><label>Nome do planejamento<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Ex.: Revisão de renda" /></label><label>Data de referência<input required type="date" value={form.referenceDate} onChange={(event) => setForm({ ...form, referenceDate: event.target.value })} /></label><label>Tipo<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value as PlanningType })}><option value="initial">Inicial</option><option value="review">Revisão</option><option value="replanning">Replanejamento</option><option value="simulation">Simulação</option></select></label><label>Observação opcional<textarea value={form.observation} onChange={(event) => setForm({ ...form, observation: event.target.value })} placeholder="Motivo ou contexto desta nova fotografia" /></label><div className="planning-actions"><button type="button" className="button secondary" onClick={onCancel}>Cancelar</button><button className="button primary" disabled={busy}>{busy ? "Criando..." : "Continuar"}</button></div></form>}</section></div> }
function DiagnosticEditor({ diagnostic, step, setStep, busy, save, complete, reopen, onView }: { diagnostic: Diagnostic; step: number; setStep: (value: number) => void; busy: boolean; save: (data: Record<string, unknown>) => Promise<void>; complete: () => Promise<void>; reopen: () => Promise<void>; onView: () => void }) { const [data, setData] = useState(diagnostic.declaredData); const saveTimer = useRef<number | null>(null); useEffect(() => setData(diagnostic.declaredData), [diagnostic.id, diagnostic.updatedAt]); useEffect(() => () => { if (saveTimer.current) window.clearTimeout(saveTimer.current); }, []); const [key, title] = STEPS[step]; const finished = diagnostic.status === "completed"; const update = (field: string, value: string) => { const next = { ...data, [field]: value }; setData(next); if (saveTimer.current) window.clearTimeout(saveTimer.current); saveTimer.current = window.setTimeout(() => void save(next), 600); };
 if (key === "review") return <section className="card diagnostic-editor"><Stepper step={step} setStep={setStep} /><p className="eyebrow">ETAPA 12 DE 12</p><h3>Revisão completa do diagnóstico</h3><DiagnosticReview data={data} onGoTo={setStep} /><label className="review-note">Observações da reunião<textarea disabled={finished} value={String(data.review ?? "")} onChange={(event) => update("review", event.target.value)} placeholder="Observações complementares do levantamento" /></label><div className="planning-actions"><button type="button" className="button secondary" onClick={() => setStep(10)}>Anterior</button>{finished ? <><button type="button" className="button secondary" onClick={onView}>Visualizar diagnóstico</button><button type="button" className="button secondary" onClick={() => void reopen()}>Reabrir diagnóstico</button></> : <button type="button" className="button primary" disabled={busy} onClick={() => void complete()}>{busy ? "Salvando..." : "Concluir diagnóstico"}</button>}</div></section>;
 return <section className="card diagnostic-editor"><Stepper step={step} setStep={setStep} /><p className="eyebrow">ETAPA {step + 1} DE {STEPS.length}</p><h3>{title}</h3><textarea disabled={finished} value={String(data[key] ?? "")} onChange={(event) => update(key, event.target.value)} placeholder={"Registre os dados declarados pelo cliente sobre " + title.toLowerCase() + "."} />{key === "workIncome" ? <label>Renda familiar mensal<input disabled={finished} type="number" value={String(data.familyIncome ?? "")} onChange={(event) => update("familyIncome", event.target.value)} /></label> : null}{key === "expenses" ? <label>Despesa familiar mensal<input disabled={finished} type="number" value={String(data.monthlyExpense ?? "")} onChange={(event) => update("monthlyExpense", event.target.value)} /></label> : null}<div className="planning-actions"><button type="button" className="button secondary" disabled={step === 0} onClick={() => setStep(step - 1)}>Anterior</button><button type="button" className="button secondary" onClick={() => setStep(step + 1)}>Próxima</button>{finished ? <button type="button" className="button secondary" onClick={onView}>Visualizar diagnóstico</button> : null}</div></section> }
function Stepper({ step, setStep }: { step: number; setStep: (value: number) => void }) { return <div className="stepper">{STEPS.map(([, label], index) => <button type="button" key={label} className={index === step ? "active" : ""} onClick={() => setStep(index)}>{index + 1}</button>)}</div> }
function DiagnosticReview({ data, onGoTo }: { data: Record<string, unknown>; onGoTo?: (index: number) => void }) { return <div className="diagnostic-review">{STEPS.slice(0, 11).map(([key, title], index) => <article key={key}><div><strong>{title}</strong><p>{String(data[key] || "Não informado")}</p>{key === "workIncome" ? <p>Renda familiar mensal: {money(data.familyIncome)}</p> : null}{key === "expenses" ? <p>Despesa familiar mensal: {money(data.monthlyExpense)}</p> : null}</div>{onGoTo ? <button type="button" className="button link" onClick={() => onGoTo(index)}>Corrigir</button> : null}</article>)}</div> }
function DiagnosticView({ workspace, onClose, onPdf }: { workspace: PopulatedWorkspace; onClose: () => void; onPdf: (mode: DiagnosticPdfMode) => Promise<void> }) { return <div className="modal-backdrop" role="presentation"><section className="card diagnostic-view" role="dialog" aria-modal="true" aria-labelledby="diagnostic-view-title"><div className="modal-title"><div><p className="eyebrow">SOMENTE LEITURA</p><h3 id="diagnostic-view-title">Diagnóstico completo</h3><p>{workspace.client.name} · {workspace.cycle.name}</p></div><button type="button" className="button secondary" onClick={onClose}>Fechar</button></div><DiagnosticReview data={workspace.diagnostic.declaredData} /><div className="pdf-actions"><div><strong>PDF para o cliente</strong><p>Somente dados declarados no diagnóstico.</p><button className="button primary" onClick={() => void onPdf("client")}>Gerar PDF para o cliente</button></div><div><strong>PDF completo interno</strong><p>Inclui a análise profissional da corretora.</p><button className="button secondary" onClick={() => void onPdf("internal")}>Gerar PDF completo interno</button></div></div></section></div> }
function AnalysisEditor({ analysis, save }: { analysis: BrokerAnalysis | null; save: (form: FormData) => Promise<void> }) { return <form className="card planning-form" action={async (form) => { await save(form); }}><p className="eyebrow">USO EXCLUSIVO DA CORRETORA</p><h3>Análise profissional</h3><textarea name="summary" defaultValue={analysis?.summary} placeholder="Resumo do caso" /><textarea name="priorities" defaultValue={analysis?.priorities} placeholder="Prioridades identificadas" /><textarea name="hypotheses" defaultValue={analysis?.hypotheses} placeholder="Hipóteses de planejamento" /><div className="two"><label>Necessidade estimada<input name="estimatedNeed" type="number" defaultValue={analysis?.estimatedNeed} /></label><label>Prazo considerado<input name="timeframe" defaultValue={analysis?.timeframe} placeholder="Ex.: 15 anos" /></label></div><textarea name="calculationNotes" defaultValue={analysis?.calculationNotes} placeholder="Observações de cálculo" /><textarea name="recommendations" defaultValue={analysis?.recommendations} placeholder="Recomendações a validar" /><textarea name="pendingQuestions" defaultValue={analysis?.pendingQuestions} placeholder="Perguntas pendentes" /><textarea name="internalNotes" defaultValue={analysis?.internalNotes} placeholder="Notas internas, não exibidas ao cliente" /><button className="button primary">Salvar análise</button></form> }
function ProposalEditor({ workspace, addVersion, present, requestRevision, close, addCatalog }: { workspace: PopulatedWorkspace; addVersion: () => Promise<void>; present: (proposal: ProposalVersion) => Promise<void>; requestRevision: (proposal: ProposalVersion) => Promise<void>; close: (proposal: ProposalVersion) => Promise<void>; addCatalog: (form: FormData) => Promise<void> }) { return <section className="proposal-area"><section className="card"><p className="eyebrow">CATÁLOGO CONFIGURÁVEL</p><h3>{workspace.catalog.insurers.map((item) => item.name).join(" · ") || "Sem seguradoras cadastradas"}</h3><p>Seguradoras, produtos e tipos de cobertura são dados configuráveis. Nenhuma marca é obrigatória no produto.</p><form className="catalog-form" action={async (form) => { await addCatalog(form); }}><select name="kind"><option value="insurer">Seguradora</option><option value="product">Produto</option><option value="coverageType">Tipo de cobertura</option></select><select name="insurerId"><option value="">Seguradora do produto</option>{workspace.catalog.insurers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input name="name" placeholder="Nome do item" required /><button className="button secondary">Adicionar ao catálogo</button></form><button className="button primary" onClick={() => void addVersion()}>Criar nova versão</button></section>{workspace.proposals.map(({ proposal, coverages }) => <article className="card proposal-card" key={proposal.id}><p className="eyebrow">VERSÃO {proposal.number} · {proposal.status}</p><h3>{money(proposal.totalMonthly)}/mês · capital protegido {money(proposal.totalProtectedCapital)}</h3><p>{proposal.revisionReason ?? "Sem motivo registrado"}. Comprometimento de renda: {proposal.incomeCommitment}%.</p>{coverages.map((coverage) => <p key={coverage.id}>{coverage.label}: {money(coverage.insuredCapital)} · {money(coverage.monthlyPremium)}/mês</p>)}<div className="planning-actions"><Link className="button secondary" href={`/apresentacao/${proposal.id}`}>Apresentação e PDF</Link>{proposal.status === "draft" ? <button className="button secondary" onClick={() => void present(proposal)}>Marcar apresentada</button> : null}{proposal.status === "presented" ? <><button className="button secondary" onClick={() => void requestRevision(proposal)}>Registrar pedido de revisão</button><button className="button primary" onClick={() => void close(proposal)}>Registrar fechamento</button></> : null}</div></article>)}</section> }
function PlanningTimeline({ events }: { events: PlanningEvent[] }) { return <section className="card planning-history"><p className="eyebrow">HISTÓRICO DO PLANEJAMENTO</p><h3>Linha do tempo</h3>{events.length ? <ol className="timeline">{events.map((event) => <li key={event.id}><time>{dateTime(event.occurredAt)}</time><span>{event.description}</span></li>)}</ol> : <p>Nenhum evento registrado ainda.</p>}</section> }
