"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { closePlanning, createProposalVersion, duplicateProposalVersion, listPlanningClients, planningWorkspace, presentProposal, removeCoverage, reorderCoverage, requestProposalRevision, saveCoverage, updateDraftProposal } from "@/application/planning-service";
import { CoverageDrawer } from "@/components/coverage-drawer";
import { ProposalDrawer } from "@/components/proposal-drawer";
import type { Client, Coverage, ProposalVersion } from "@/domains/core/entities";

const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
type Workspace = Awaited<ReturnType<typeof planningWorkspace>>;
type CoverageEditor = { proposal: ProposalVersion; coverage?: Coverage };
type ProposalEditor = { proposal: ProposalVersion; coverages: Coverage[] };

export function ProposalWorkspace() {
  const [clients, setClients] = useState<Client[]>([]);
  const [clientId, setClientId] = useState("");
  const [workspace, setWorkspace] = useState<Workspace | null>(null);
  const [notice, setNotice] = useState("");
  const [coverageEditor, setCoverageEditor] = useState<CoverageEditor | null>(null);
  const [proposalEditor, setProposalEditor] = useState<ProposalEditor | null>(null);
  const refresh = useCallback(async (id: string) => { if (id) setWorkspace(await planningWorkspace(id)); }, []);
  useEffect(() => { void (async () => { const rows = await listPlanningClients(); setClients(rows); if (rows[0]) { setClientId(rows[0].id); await refresh(rows[0].id); } })(); }, [refresh]);

  const addVersion = async () => { if (!workspace?.cycle || !workspace.diagnostic) return; await createProposalVersion(workspace.cycle, workspace.diagnostic, workspace.analysis, workspace.proposals.length ? "Revisão da proposta" : "Primeira versão"); await refresh(clientId); setNotice("Nova versão criada."); };
  const act = async (proposal: ProposalVersion, action: "present" | "duplicate" | "revision" | "close") => { if (!workspace?.cycle) return; if (action === "present") await presentProposal(proposal); if (action === "duplicate") await duplicateProposalVersion(proposal); if (action === "revision") await requestProposalRevision(workspace.cycle, proposal); if (action === "close") await closePlanning(workspace.cycle, proposal, proposal.createdAt.slice(0, 10)); await refresh(clientId); setNotice(action === "duplicate" ? "Nova versão criada a partir da selecionada." : action === "present" ? "Versão marcada como apresentada e protegida contra alterações." : "Alteração registrada."); };
  const persistCoverage = async (editor: CoverageEditor, input: Parameters<typeof saveCoverage>[1]) => { await saveCoverage(editor.proposal.id, input); await refresh(clientId); setNotice(editor.coverage ? "Cobertura atualizada." : "Cobertura adicionada."); };
  const deleteCoverage = async (editor: CoverageEditor) => { if (!editor.coverage) return; await removeCoverage(editor.proposal.id, editor.coverage.id); setCoverageEditor(null); await refresh(clientId); setNotice("Cobertura removida do rascunho."); };
  const moveCoverage = async (editor: CoverageEditor, direction: "up" | "down") => { if (!editor.coverage) return; await reorderCoverage(editor.proposal.id, editor.coverage.id, direction); await refresh(clientId); setNotice("Ordem das coberturas atualizada."); };
  const saveProposal = async (editor: ProposalEditor, input: { revisionReason: string; generalNote: string }) => { await updateDraftProposal(editor.proposal.id, input); await refresh(clientId); setNotice("Versão em rascunho atualizada."); };

  return <div className="page planning-page">
    <section className="hero"><div><p className="eyebrow">PROPOSTAS</p><h2>Propostas versionadas</h2><p>Seguradoras, produtos e tipos de cobertura são consultados exclusivamente no Catálogo.</p></div><Link className="button secondary" href="/catalogo">Abrir Catálogo</Link></section>
    <section className="card planning-toolbar"><label>Cliente<select value={clientId} onChange={(event) => { setClientId(event.target.value); void refresh(event.target.value); }}><option value="">Selecione</option>{clients.map((client) => <option value={client.id} key={client.id}>{client.name}</option>)}</select></label><button className="button primary" disabled={!workspace?.cycle || !workspace.diagnostic} onClick={() => void addVersion()}>Criar nova versão</button></section>
    {notice ? <p className="notice" role="status">{notice}</p> : null}
    {workspace?.cycle ? <section className="proposal-area">{workspace.proposals.map(({ proposal, coverages }) => <article className="card proposal-card" key={proposal.id}><p className="eyebrow">VERSÃO {proposal.number} · {proposal.status === "draft" ? "RASCUNHO" : proposal.status === "presented" ? "APRESENTADA" : proposal.status === "accepted" ? "ACEITA" : "SUBSTITUÍDA"}</p><h3>{money(proposal.totalMonthly)}/mês · capital protegido {money(proposal.totalProtectedCapital)}</h3><p>{proposal.generalNote || "Sem observação geral."}</p><section className="coverage-list"><div className="section-heading"><div><h4>Coberturas</h4><p>{coverages.length} registro(s) vinculado(s) a esta versão.</p></div>{proposal.status === "draft" ? <button className="button secondary" onClick={() => setCoverageEditor({ proposal })}>Adicionar cobertura</button> : null}</div>{coverages.length ? <div className="crm-list">{coverages.map((coverage) => <article className="card lead-row" key={coverage.id}><div><h3>{coverage.label}</h3><p>{coverage.coverageType || "Tipo não informado"} · {coverage.term || "Vigência não informada"}</p><small>{money(coverage.insuredCapital ?? 0)} de capital · {money(coverage.monthlyPremium ?? 0)}/mês</small></div>{proposal.status === "draft" ? <div className="lead-actions"><button className="button secondary" onClick={() => setCoverageEditor({ proposal, coverage })}>Editar</button><button className="text-button" onClick={() => void moveCoverage({ proposal, coverage }, "up")}>Subir</button><button className="text-button" onClick={() => void moveCoverage({ proposal, coverage }, "down")}>Descer</button></div> : <span>Protegida</span>}</article>)}</div> : <p>Nenhuma cobertura nesta versão. Cadastre os itens mestres no Catálogo e adicione a cobertura ao rascunho.</p>}</section><div className="planning-actions"><Link className="button secondary" href={`/apresentacao/${proposal.id}`}>Apresentação e PDF</Link>{proposal.status === "draft" ? <button className="button primary" onClick={() => setProposalEditor({ proposal, coverages })}>Editar versão</button> : proposal.status === "presented" ? <><button className="button secondary" onClick={() => void act(proposal, "revision")}>Gerar revisão</button><button className="button primary" onClick={() => void act(proposal, "close")}>Registrar fechamento</button></> : null}</div></article>)}</section> : <section className="card empty-state"><h3>Selecione um cliente e planejamento</h3><p>O Catálogo é mantido fora desta tela.</p></section>}
    {coverageEditor && workspace ? <CoverageDrawer proposal={coverageEditor.proposal} coverage={coverageEditor.coverage} catalog={workspace.catalog} onClose={() => setCoverageEditor(null)} onSave={(input) => persistCoverage(coverageEditor, input)} onRemove={coverageEditor.coverage ? () => deleteCoverage(coverageEditor) : undefined} onMove={coverageEditor.coverage ? (direction) => moveCoverage(coverageEditor, direction) : undefined} /> : null}
    {proposalEditor && workspace?.cycle ? <ProposalDrawer proposal={proposalEditor.proposal} planningReferenceDate={workspace.cycle.referenceDate} coverages={proposalEditor.coverages} insurerName={workspace.catalog.insurers.find((insurer) => insurer.id === proposalEditor.coverages[0]?.insurerId)?.name} productName={workspace.catalog.products.find((product) => product.id === proposalEditor.coverages[0]?.productId)?.name} onClose={() => setProposalEditor(null)} onSave={(input) => saveProposal(proposalEditor, input)} onManageCoverage={() => { setProposalEditor(null); setCoverageEditor({ proposal: proposalEditor.proposal }); }} onDuplicate={async () => { await act(proposalEditor.proposal, "duplicate"); setProposalEditor(null); }} onPresent={async () => { if (window.confirm("Marcar esta versão como apresentada? Ela ficará protegida contra alterações.")) { await act(proposalEditor.proposal, "present"); setProposalEditor(null); } }} /> : null}
  </div>;
}
