"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { listHistoricalReportRows } from "@/application/report-history-service";

const labels = { commercial_proposal: "Apresentação e PDF comercial", diagnostic_client: "Diagnóstico do cliente", diagnostic_internal: "Diagnóstico interno" } as const;
const date = (value: string) => new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));

export function ReportsWorkspace() {
  const [rows, setRows] = useState<Awaited<ReturnType<typeof listHistoricalReportRows>>>([]); const [query, setQuery] = useState(""); const [type, setType] = useState<"all" | keyof typeof labels>("all"); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { void (async () => { try { setRows(await listHistoricalReportRows()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível carregar os relatórios."); } finally { setLoading(false); } })(); }, []);
  const filtered = useMemo(() => rows.filter((row) => (type === "all" || row.snapshot.type === type) && `${row.clientName} ${row.planningName} ${labels[row.snapshot.type]}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())), [rows, query, type]);
  return <div className="page reports-page"><section className="hero"><div><p className="eyebrow">CENTRAL DE RELATÓRIOS</p><h2>Documentos e snapshots históricos</h2><p>Um relatório reaberto sempre usa a fotografia gravada no momento da geração.</p></div><Link className="button secondary" href="/planejamentos">Gerar documentos</Link></section><section className="card portfolio-filters"><label>Pesquisar<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cliente ou planejamento" /></label><label>Tipo<select value={type} onChange={(event) => setType(event.target.value as typeof type)}><option value="all">Todos os tipos</option><option value="diagnostic_client">Diagnóstico do cliente</option><option value="diagnostic_internal">Diagnóstico interno</option><option value="commercial_proposal">Apresentação e PDF comercial</option></select></label></section>{error ? <p className="form-error" role="alert">{error}</p> : null}{loading ? <section className="card empty-state"><h3>Carregando relatórios...</h3></section> : !rows.length ? <section className="card empty-state"><h3>Nenhum documento gerado ainda</h3><p>Os relatórios aparecerão aqui depois de gerados nos fluxos de diagnóstico e proposta.</p><Link className="button primary" href="/planejamentos">Abrir planejamentos</Link></section> : !filtered.length ? <section className="card empty-state"><h3>Nenhum relatório encontrado</h3><p>Ajuste a pesquisa ou o filtro para localizar outro documento.</p></section> : <section className="reports-list">{filtered.map((row) => { const snapshot = row.snapshot; const commercial = snapshot.type === "commercial_proposal"; const view = commercial && snapshot.proposalVersionId ? `/apresentacao/${snapshot.proposalVersionId}` : `/relatorios/${snapshot.id}`; return <article className="card report-row" key={snapshot.id}><div><p className="eyebrow">{labels[snapshot.type]}</p><h3>{row.clientName}</h3><p>{row.planningName}{row.proposalNumber ? ` · Proposta v${row.proposalNumber}` : ""}</p><dl><div><dt>Gerado em</dt><dd>{date(snapshot.generatedAt)}</dd></div><div><dt>Origem</dt><dd>Snapshot imutável</dd></div><div><dt>Template</dt><dd>{snapshot.templateVersion}</dd></div></dl></div><div className="portfolio-actions"><Link className="button primary" href={view}>{commercial ? "Visualizar e baixar" : "Visualizar"}</Link><Link className="button secondary" href={`/clientes/${snapshot.clientId}`}>Cliente</Link><Link className="button secondary" href={`/planejamentos?clientId=${snapshot.clientId}&planningId=${snapshot.planningCycleId}`}>Planejamento</Link>{snapshot.proposalVersionId ? <Link className="button secondary" href={`/apresentacao/${snapshot.proposalVersionId}`}>Proposta</Link> : null}</div></article>; })}</section>}</div>;
}
