"use client";

import Link from "next/link";
import { useEffect, useState, type CSSProperties } from "react";
import { generateCommercialProposalPdf } from "@/application/commercial-proposal-pdf-service";
import { brokerDashboard, clientDashboard, commercialReport, type BrokerDashboard, type CommercialReportPayload } from "@/application/reporting-service";
import { STAGE_LABEL } from "@/application/crm-service";
import type { PipelineStage } from "@/domains/core/entities";
import { clientStatusLabel, proposalStatusLabel } from "@/lib/status-labels";
import { AegisPanel } from "@/components/aegis-panel";

const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });
const date = (value?: string) => value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium" }).format(new Date(value)) : "Não informado";
const typeLabel = { initial: "Inicial", review: "Revisão", replanning: "Replanejamento", simulation: "Simulação" };

export function BrokerDashboardWorkspace() {
  const [data, setData] = useState<BrokerDashboard | null>(null); const [months, setMonths] = useState(6); const [selected, setSelected] = useState<BrokerDashboard["metrics"][number] | null>(null); const [error, setError] = useState("");
  useEffect(() => { void brokerDashboard(months).then(setData).catch((reason) => setError(reason instanceof Error ? reason.message : "Não foi possível carregar o dashboard.")); }, [months]);
  if (error) return <div className="page"><section className="empty"><h2>Dashboard indisponível</h2><p>{error}</p></section></div>;
  return <div className="page reporting-page">
    <section className="hero"><div><p className="eyebrow">GESTÃO DA CORRETORA</p><h2>Visão comercial e de proteção financeira</h2><p>Indicadores calculados exclusivamente a partir do CRM, Kanban, planejamentos, propostas e fechamentos persistidos.</p></div><label className="period-select">Período<select value={months} onChange={(event) => setMonths(Number(event.target.value))}><option value={3}>Últimos 3 meses</option><option value={6}>Últimos 6 meses</option><option value={12}>Últimos 12 meses</option></select></label></section>
    <section className="reporting-metrics">{data?.metrics.map((metric) => <button className="card metric-button" key={metric.key} onClick={() => setSelected(metric)}><p>{metric.label}</p><strong>{metric.suffix === " BRL" ? money(metric.value) : `${metric.value}${metric.suffix ?? ""}`}</strong><span>{metric.detail} · abrir registros</span></button>)}</section>
    <section className="reporting-grid"><article className="card report-wide"><p className="eyebrow">FUNIL COMERCIAL</p><h3>Distribuição atual do pipeline</h3><p>Mostra a posição atual dos registros. A taxa de conversão é calculada separadamente pelos fechamentos válidos.</p><div className="funnel-rows">{data?.funnel.map((item) => <Link key={item.stage} href={`/kanban?stage=${item.stage}`}><span>{item.label}</span><b>{item.count}</b><i style={{ width: `${Math.max(5, item.topPercent)}%` }} /><small>{item.topPercent}% dos registros atuais</small></Link>)}</div></article><article className="card"><p className="eyebrow">AGING</p><h3>Oportunidades paradas</h3><div className="aging-list">{data?.aging.map((item) => <Link className={item.urgent && item.count ? "urgent" : ""} href={`/kanban?aging=${item.label}`} key={item.label}><span>{item.label}</span><b>{item.count}</b><small>{item.urgent ? "Exige ação" : "Acompanhar"}</small></Link>)}</div></article></section>
    <section className="reporting-grid"><TrendChart title="Leads, propostas e fechamentos" rows={data?.evolution ?? []} keys={["leads", "proposals", "closings"]} /><TrendChart title="Prêmio mensal contratado" rows={data?.evolution ?? []} keys={["monthlyPremium"]} monetary /><TrendChart title="Capital protegido" rows={data?.evolution ?? []} keys={["protectedCapital"]} monetary /></section>
    {selected ? <MetricRecords metric={selected} onClose={() => setSelected(null)} /> : null}
  </div>;
}

function TrendChart({ title, rows, keys, monetary = false }: { title: string; rows: BrokerDashboard["evolution"]; keys: Array<"leads" | "proposals" | "closings" | "monthlyPremium" | "protectedCapital">; monetary?: boolean }) { const max = Math.max(1, ...rows.flatMap((row) => keys.map((key) => row[key] as number))); return <article className="card trend-chart"><p className="eyebrow">EVOLUÇÃO TEMPORAL</p><h3>{title}</h3><div className="chart-bars">{rows.map((row) => <div className="chart-month" key={row.month}>{keys.map((key, index) => <i key={key} className={`bar bar-${index}`} style={{ height: `${Math.max(3, ((row[key] as number) / max) * 100)}%` }} title={`${key}: ${monetary ? money(row[key] as number) : row[key]}`} />)}<span>{row.label}</span></div>)}</div><p className="chart-legend">{keys.map((key) => <span key={key}>{key === "monthlyPremium" ? "Prêmio" : key === "protectedCapital" ? "Capital" : key === "leads" ? "Leads" : key === "proposals" ? "Propostas" : "Fechamentos"}</span>)}</p></article> }

function MetricRecords({ metric, onClose }: { metric: BrokerDashboard["metrics"][number]; onClose: () => void }) { return <div className="modal-backdrop"><section className="card metric-records" role="dialog" aria-modal="true"><div className="modal-title"><div><p className="eyebrow">INDICADOR OPERACIONAL</p><h3>{metric.label}</h3><p>{metric.detail}</p></div><button className="button secondary" onClick={onClose}>Fechar</button></div>{metric.stage ? <Link className="button primary" href={`/kanban?stage=${metric.stage}`}>Abrir Kanban filtrado</Link> : null}<div className="metric-record-list">{metric.records.length ? metric.records.map((record) => <Link key={record.id} href={record.href}><b>{record.label}</b><span>{record.detail}</span></Link>) : <p>Nenhum registro compõe este indicador no período selecionado.</p>}</div></section></div> }

export function ClientDashboardWorkspace({ clientId }: { clientId: string }) { const [data, setData] = useState<Awaited<ReturnType<typeof clientDashboard>> | null>(null); const [error, setError] = useState(""); useEffect(() => { void clientDashboard(clientId).then(setData).catch((reason) => setError(reason instanceof Error ? reason.message : "Não foi possível carregar o cliente.")); }, [clientId]); if (error) return <div className="page"><section className="empty"><h2>Cliente indisponível</h2><p>{error}</p></section></div>; if (!data) return <div className="page"><section className="empty"><h2>Carregando cliente...</h2></section></div>; if (!data.client) return <div className="page"><section className="empty"><h2>Cliente não encontrado</h2></section></div>;
  return <div className="page reporting-page client-dashboard"><section className="hero"><div><p className="eyebrow">VISÃO CONSOLIDADA DO CLIENTE</p><h2>{data.client.name}</h2><p>{data.client.pipelineStage ? STAGE_LABEL[data.client.pipelineStage] : `Cliente ${clientStatusLabel(data.client.status).toLowerCase()}`} · {data.current?.name ?? "Sem planejamento atual"}</p></div><div className="quick-actions"><Link className="button secondary" href="/clientes">Cadastro</Link>{data.current ? <Link className="button secondary" href="/diagnosticos">Diagnóstico atual</Link> : null}{data.presented ? <Link className="button primary" href={`/apresentacao/${data.presented.id}`}>Apresentar proposta</Link> : null}</div></section>
    <section className="client-summary"><article className="card"><p>Próxima revisão</p><strong>{date(data.closing?.suggestedReviewAt)}</strong></article><article className="card"><p>Última proposta apresentada</p><strong>{data.presented ? `v${data.presented.number}` : "Nenhuma"}</strong></article><article className="card"><p>Planejamento atual</p><strong>{data.current ? `${typeLabel[data.current.type]} · ${date(data.current.referenceDate)}` : "Não iniciado"}</strong></article></section>
    <section className="reporting-grid"><article className="card"><p className="eyebrow">RESUMO FINANCEIRO</p><h3>Fotografia declarada</h3><dl className="client-facts"><div><dt>Renda familiar</dt><dd>{money(data.finance.familyIncome)}</dd></div><div><dt>Despesa mensal</dt><dd>{money(data.finance.monthlyExpense)}</dd></div><div><dt>Patrimônio</dt><dd>{data.finance.assets}</dd></div><div><dt>Reservas</dt><dd>{data.finance.reserves}</dd></div><div><dt>Dívidas</dt><dd>{data.finance.debts}</dd></div><div><dt>Comprometimento</dt><dd>{data.finance.commitment}%</dd></div></dl></article><article className="card"><p className="eyebrow">PROTEÇÃO</p><h3>Proposta selecionada</h3><dl className="client-facts"><div><dt>Prêmio mensal</dt><dd>{money(data.protection.monthly)}</dd></div><div><dt>Prêmio anual</dt><dd>{money(data.protection.annual)}</dd></div><div><dt>Capital segurado</dt><dd>{money(data.protection.capital)}</dd></div><div><dt>Objetivos protegidos</dt><dd>{data.protection.objectives.join(" · ") || "A definir"}</dd></div></dl><div className="coverage-list">{data.protection.coverages.map((coverage) => <span key={coverage.id}>{coverage.label} · {coverage.term ?? "Vigência a definir"}</span>)}</div></article></section>
    <AegisPanel clientId={clientId} proposal={data.accepted ?? data.presented ?? data.proposals.at(-1)} />
    <section className="reporting-grid"><article className="card"><p className="eyebrow">HISTÓRICO</p><h3>Planejamentos e propostas</h3><div className="client-history">{data.proposals.map((proposal) => <Link href={`/apresentacao/${proposal.id}`} key={proposal.id}>Proposta v{proposal.number} · {proposalStatusLabel[proposal.status]}</Link>)}{data.current ? <Link href="/planejamentos">Histórico de planejamentos</Link> : null}<Link href="/backup">Documentos gerados ({data.snapshots.length})</Link></div></article><article className="card"><p className="eyebrow">LINHA DO TEMPO</p><h3>Relacionamento</h3><ol className="timeline">{data.timeline.slice(0, 9).map((item, index) => <li key={`${item.at}-${index}`}><time>{date(item.at)}</time><span>{item.label}</span></li>)}</ol></article></section>
  </div>;
}

export function ProposalPresentationWorkspace({ proposalId }: { proposalId: string }) { const [data, setData] = useState<{ report: CommercialReportPayload } | null>(null); const [step, setStep] = useState(0); const [error, setError] = useState(""); useEffect(() => { void commercialReport(proposalId).then(setData).catch((reason) => setError(reason instanceof Error ? reason.message : "Não foi possível abrir a apresentação.")); }, [proposalId]); if (error) return <main className="presentation-page"><p>{error}</p></main>; if (!data) return <main className="presentation-page"><p>Preparando apresentação...</p></main>;
  const report = data.report; const slides = [<><p className="eyebrow">{report.brand.value.clientName}</p><h1>Planejamento de Proteção Financeira</h1><h2>{report.client.value.name}</h2><p>{report.planning.value.name} · Proposta v{report.proposal.value.number}</p></>, <><p className="eyebrow">OBJETIVOS E DIAGNÓSTICO</p><h2>O que importa para este planejamento</h2><p>{String(report.diagnosis.value.goals ?? "Objetivos a validar com o cliente.")}</p><p>{String(report.diagnosis.value.family ?? "Informações familiares registradas no diagnóstico.")}</p></>, <><p className="eyebrow">PLANEJAMENTO DA CORRETORA</p><h2>Prioridades de proteção</h2><p>{report.analysis.value?.priorities ?? "Prioridades a validar."}</p><p>{report.analysis.value?.recommendations ?? report.analysis.value?.summary ?? "Análise profissional em construção."}</p></>, <><p className="eyebrow">PROPOSTA DE PROTEÇÃO</p><h2>Coberturas e finalidades</h2>{report.coverages.value.map((coverage) => <article key={coverage.label}><b>{coverage.label}</b><span>{coverage.objective}</span><strong>{money(coverage.insuredCapital ?? 0)} de capital segurado</strong></article>)}</>, <><p className="eyebrow">RESUMO</p><h2>Investimento e proteção</h2><dl><div><dt>Prêmio mensal</dt><dd>{money(report.proposal.value.totalMonthly)}</dd></div><div><dt>Prêmio anual</dt><dd>{money(report.proposal.value.totalAnnual)}</dd></div><div><dt>Capital segurado</dt><dd>{money(report.proposal.value.totalProtectedCapital)}</dd></div><div><dt>Comprometimento da renda</dt><dd>{report.proposal.value.incomeCommitment}%</dd></div></dl><p>{report.brand.value.phone} · {report.brand.value.email}</p></>];
  const fullscreen = () => { void document.documentElement.requestFullscreen?.(); };
  return <main className="presentation-page" style={{ "--presentation-accent": report.brand.value.primaryColor, "--presentation-highlight": report.brand.value.highlightColor } as CSSProperties}><section className="presentation-slide">{slides[step]}</section><footer><button aria-label="Anterior" disabled={step === 0} onClick={() => setStep(step - 1)}>← Anterior</button><span>{step + 1} / {slides.length}</span><button onClick={() => setStep(step + 1)} disabled={step === slides.length - 1}>Próximo →</button><button onClick={fullscreen}>Tela cheia</button><button onClick={() => generateCommercialProposalPdf(report)}>Baixar PDF</button></footer></main>;
}
