import type { EntityMetadata } from "@/domains/shared/entity";
export type Tenant = EntityMetadata & { name: string };
export type BrandSettings = EntityMetadata & { clientName: string; logoUrl?: string; primaryColor: string; highlightColor: string; phone: string; email: string; address?: string };
export const PIPELINE_STAGES = ["new", "form", "calculation", "in_progress", "ready", "presented", "waiting", "closed", "lost"] as const;
export type PipelineStage = (typeof PIPELINE_STAGES)[number];
export type Lead = EntityMetadata & { name: string; email?: string; phone?: string; origin?: string; referredBy?: string; profession?: string; city?: string; notes?: string; nextAction?: string; nextActionAt?: string; tags?: string[]; stage: PipelineStage; archivedAt?: string | null; potentialValue?: number; priority?: "low" | "normal" | "high" };
export type Client = EntityMetadata & { name: string; sourceLeadId?: string; cpf?: string; birthDate?: string; maritalStatus?: string; email?: string; phone?: string; profession?: string; company?: string; address?: string; status: "active" | "inactive"; notes?: string; pipelineStage?: PipelineStage; nextAction?: string; nextActionAt?: string; potentialValue?: number };
export type Task = EntityMetadata & { title: string; dueDate?: string; status: "open" | "done"; relatedId?: string };
export type PlanningType = "initial" | "review" | "replanning" | "simulation";
export type PlanningCycle = EntityMetadata & { clientId: string; name: string; type: PlanningType; referenceDate: string; observation?: string; status: "draft" | "active" | "closed" | "cancelled"; startedAt: string; suggestedReviewAt?: string; acceptedProposalVersionId?: string };
export type PlanningEventType = "planning_created" | "diagnostic_started" | "diagnostic_completed" | "diagnostic_reopened" | "analysis_updated" | "proposal_created" | "proposal_presented" | "proposal_revision_requested" | "proposal_accepted" | "closing_recorded" | "planning_closed";
export type PlanningEvent = EntityMetadata & { clientId: string; planningCycleId: string; type: PlanningEventType; description: string; occurredAt: string; proposalVersionId?: string };
export type Diagnostic = EntityMetadata & { clientId: string; planningCycleId: string; planningCycle: string; status: "draft" | "completed" | "reopened"; declaredData: Record<string, unknown>; completedAt?: string };
export type BrokerAnalysis = EntityMetadata & { clientId: string; planningCycleId: string; summary?: string; priorities?: string; hypotheses?: string; estimatedNeed?: number; timeframe?: string; calculationNotes?: string; recommendations?: string; pendingQuestions?: string; internalNotes?: string };
export type Insurer = EntityMetadata & { name: string; active: boolean };
export type InsuranceProduct = EntityMetadata & { insurerId: string; name: string; category?: string; active: boolean };
export type CoverageType = EntityMetadata & { name: string; active: boolean };
export type ProposalStatus = "draft" | "presented" | "accepted" | "superseded";
export type ProposalVersion = EntityMetadata & { clientId: string; planningCycleId: string; planId?: string; number: number; status: ProposalStatus; generalNote?: string; revisionReason?: string; presentedAt?: string; totalMonthly: number; totalAnnual: number; totalProtectedCapital: number; incomeCommitment: number };
export type Coverage = EntityMetadata & { proposalVersionId: string; insurerId?: string; productId?: string; coverageType?: string; label: string; objective?: string; insuredCapital?: number; term?: string; monthlyPremium?: number; description?: string; brokerNote?: string; displayOrder: number; name: string };
export type ClosingRecord = EntityMetadata & { clientId: string; planningCycleId: string; proposalVersionId: string; closedAt: string; suggestedReviewAt?: string };
export type Plan = EntityMetadata & { clientId: string; name: string; status: "draft" | "active" };
export type PipelineHistory = EntityMetadata & { leadId?: string; clientId?: string; fromStage?: PipelineStage; toStage: PipelineStage; changedAt: string; reason?: string; eventType?: "created" | "moved" | "converted" | "diagnostic_completed" | "proposal_presented" | "closed" };
export type MetisAnalysisType = "diagnostic" | "proposal_review" | "meeting_questions";
export type MetisStructuredResult = {
  summary: string;
  attentionPoints: string[];
  protectionTopics: string[];
  questions: string[];
  missingInformation: string[];
  proposalReview?: { alignedItems: string[]; reviewItems: string[] };
  disclaimer: string;
};
export type MetisUsage = { inputTokens?: number; outputTokens?: number; totalTokens?: number };
export type MetisSanitizationEvidence = {
  version: "metis-context-v2";
  sentSections: string[];
  excludedCategories: string[];
  healthIncluded: boolean;
};
export type AiAnalysis = EntityMetadata & {
  clientId: string;
  planningCycleId: string;
  proposalVersionId?: string;
  analysisType: MetisAnalysisType;
  inputFingerprint: string;
  provider: string;
  model: string;
  status: "complete" | "failed";
  structuredResult?: MetisStructuredResult;
  errorMessage?: string;
  errorCode?: string;
  retryable?: boolean;
  durationMs?: number;
  usage?: MetisUsage;
  sanitization?: MetisSanitizationEvidence;
};
export type ReportDataOrigin = "clientProvided" | "systemCalculated" | "brokerAnalysis" | "templateStatic";
export type ReportSnapshot = EntityMetadata & {
  clientId: string;
  planningCycleId: string;
  proposalVersionId?: string;
  type: "commercial_proposal" | "diagnostic_client" | "diagnostic_internal";
  generatedAt: string;
  templateVersion: string;
  payload: Record<string, unknown>;
};

export const COMMERCIAL_ACTIVITY_TYPES = ["ab_phone", "approach_scheduled", "approach_completed", "closing_scheduled", "closing_completed", "proposal", "recommendation"] as const;
export type CommercialActivityType = (typeof COMMERCIAL_ACTIVITY_TYPES)[number];
export type CommercialActivityStatus = "planned" | "completed" | "cancelled";
export type CommercialContactStage = "market_base" | "hot40" | "opportunity" | "client";
export type Contact = EntityMetadata & { fullName: string; email?: string; phone?: string; origin?: string; consultant?: string; status: "active" | "inactive"; commercialStage: CommercialContactStage; notes?: string };
export type ProspectQualification = EntityMetadata & { contactId: string; status: "pending" | "qualified" | "not_qualified"; source?: string; notes?: string; qualifiedAt?: string; sourceId?: string; incomeBandId?: string; ageRangeId?: string; maritalStatusId?: string; childrenId?: string; contactFrequencyId?: string; approachEaseId?: string; referralPotentialId?: string; estimatedMonthlyIncome?: number; profession?: string; originDate?: string };
export type Hot40Membership = EntityMetadata & { contactId: string; status: "active" | "paused" | "converted" | "removed"; enteredAt: string; stage?: Hot40Stage; stageChangedAt?: string; priority?: "low" | "normal" | "high"; notes?: string };
export const HOT40_STAGES = ["ab_phone", "approach_scheduled", "approach_completed", "closing_scheduled", "closing_completed", "proposal"] as const;
export type Hot40Stage = (typeof HOT40_STAGES)[number];
export type Hot40StageEvent = EntityMetadata & { contactId: string; membershipId: string; fromStage?: Hot40Stage; toStage: Hot40Stage; occurredAt: string; notes?: string };
export type CommercialActivity = EntityMetadata & { contactId: string; type: CommercialActivityType; status: CommercialActivityStatus; scheduledAt?: string; completedAt?: string; notes?: string; createdBy?: string };
export type CommercialOpportunity = EntityMetadata & { contactId: string; title: string; status: "open" | "won" | "lost"; source?: string; expectedAt?: string; notes?: string };
export type CommercialGoal = EntityMetadata & { name: string; target: number; periodStart: string; periodEnd: string; status: "active" | "closed"; notes?: string };
export type CommercialBenchmark = EntityMetadata & { year: number; month: number; activityType: CommercialActivityType; weeklyTarget: number; monthlyTarget: number };
export type Referral = EntityMetadata & { contactId: string; referredContactId?: string; status: "new" | "contacted" | "converted" | "discarded"; notes?: string };
export type Notification = EntityMetadata & { contactId?: string; title: string; message: string; type: "info" | "warning" | "success"; status: "unread" | "read"; readAt?: string };

export const COMMERCIAL_PARAMETER_GROUPS = ["source", "income_band", "age_range", "marital_status", "children", "contact_frequency", "approach_ease", "referral_potential"] as const;
export type CommercialParameterGroup = (typeof COMMERCIAL_PARAMETER_GROUPS)[number];
export type CommercialParameter = EntityMetadata & { group: CommercialParameterGroup; label: string; order: number; active: boolean };
