import Link from "next/link";

const steps = [
  { number: "01", name: "Lead", objective: "Registrar a oportunidade inicial e não perder o contexto do primeiro contato.", where: "CRM → Leads", action: "Cadastre nome, origem, contato, necessidade inicial, próxima ação e prioridade.", done: "O lead está identificado e possui uma próxima ação definida.", result: "Uma oportunidade pronta para acompanhamento comercial.", href: "/leads", button: "Abrir leads" },
  { number: "02", name: "Kanban", objective: "Organizar o trabalho comercial pela etapa real de cada oportunidade.", where: "Principal → Kanban", action: "Mova o lead ou cliente conforme a evolução, registre o motivo e acompanhe oportunidades paradas.", done: "A etapa representa a situação atual e a próxima ação está clara.", result: "Pipeline e indicadores atualizados pelo histórico real.", href: "/kanban", button: "Abrir Kanban" },
  { number: "03", name: "Cliente", objective: "Transformar o lead atendido em cadastro permanente, sem redigitação.", where: "CRM → Clientes", action: "Promova o lead quando houver atendimento qualificado e complete os dados permanentes do cliente.", done: "O cliente está cadastrado e vinculado à sua origem comercial.", result: "Base para novos planejamentos e revisões futuras.", href: "/clientes", button: "Abrir clientes" },
  { number: "04", name: "Planejamento", objective: "Criar a fotografia do cliente para uma data e contexto específicos.", where: "Operação → Planejamentos", action: "Informe nome, data de referência, tipo e observação. Crie um novo quando houver mudança relevante de contexto.", done: "Existe um planejamento ativo com contexto e data definidos.", result: "Diagnóstico, análise, propostas e fechamento ficam organizados no mesmo histórico.", href: "/planejamentos", button: "Abrir planejamentos" },
  { number: "05", name: "Diagnóstico", objective: "Coletar os dados declarados pelo cliente de forma estruturada.", where: "Operação → Diagnósticos ou dentro do Planejamento", action: "Preencha as etapas de identificação, família, renda, despesas, patrimônio, reservas, dívidas, seguros, saúde, objetivos e revisão final.", done: "A revisão consolidada foi conferida e o diagnóstico foi concluído.", result: "Uma tarefa é direcionada para A calcular no Kanban.", href: "/diagnosticos", button: "Abrir diagnósticos" },
  { number: "06", name: "Análise", objective: "Registrar a interpretação profissional da corretora separada do que foi declarado pelo cliente.", where: "Operação → Planejamentos", action: "Preencha prioridades, hipóteses, necessidade estimada, recomendações, pendências e notas internas.", done: "A análise profissional está revisada e há base para montar a solução.", result: "Critérios claros para cálculo e proposta, preservando a autoria da corretora.", href: "/planejamentos", button: "Abrir análise" },
  { number: "07", name: "Proposta", objective: "Montar a solução de proteção e manter suas versões rastreáveis.", where: "Operação → Propostas", action: "Crie a proposta com coberturas, finalidade, capital segurado, prazo, prêmio e justificativa. Para ajustes do mesmo contexto, crie uma nova versão.", done: "A versão está completa e pronta para revisão ou apresentação.", result: "Alternativas comerciais preservadas sem apagar versões anteriores.", href: "/propostas", button: "Abrir propostas" },
  { number: "08", name: "Apresentação", objective: "Apresentar uma versão específica da proposta sem controles administrativos.", where: "Operação → Propostas", action: "Escolha a versão, registre a apresentação e abra a visualização web ou o PDF comercial.", done: "A versão apresentada está identificada no histórico do planejamento.", result: "Apresentação web e PDF comercial reproduzíveis pela versão selecionada.", href: "/propostas", button: "Abrir apresentação" },
  { number: "09", name: "Fechamento", objective: "Registrar a decisão do cliente vinculada à versão efetivamente aceita.", where: "Operação → Planejamentos", action: "Selecione uma proposta apresentada, registre o aceite e indique a próxima revisão quando aplicável.", done: "O fechamento aponta para uma versão aceita e o planejamento está encerrado.", result: "Kanban, dashboards e carteira refletem o prêmio e o capital contratado.", href: "/planejamentos", button: "Abrir fechamentos" },
  { number: "10", name: "Carteira", objective: "Acompanhar clientes com proteção contratada e manter o relacionamento ativo.", where: "CRM → Clientes", action: "Use o dashboard do cliente para consultar proteção atual, histórico, proposta selecionada e próxima revisão.", done: "O cliente fechado aparece como ativo e possui acompanhamento previsto.", result: "Visão de carteira baseada em fechamentos válidos, sem valores simulados.", href: "/clientes", button: "Abrir carteira" },
  { number: "11", name: "Revisão", objective: "Atualizar a proteção quando houver nova necessidade, sem sobrescrever o passado.", where: "Operação → Planejamentos", action: "Crie um novo planejamento do tipo revisão, replanejamento ou simulação e repita o fluxo com a nova fotografia.", done: "A nova fotografia possui seu próprio diagnóstico, análise e versões de proposta.", result: "Histórico completo de evolução do cliente ao longo do tempo.", href: "/planejamentos", button: "Iniciar revisão" },
] as const;

const faqs = [
  ["Planejamento x versão da proposta", "Planejamento é a fotografia do cliente em um contexto e data. Versão é um ajuste da solução dentro daquele mesmo planejamento. Mudou a solução, crie versão. Mudou a fotografia ou o contexto, crie planejamento."],
  ["Modo local", "No MVP, os dados ficam no IndexedDB deste navegador e dispositivo. Outro computador não mostra esta base automaticamente."],
  ["Backup", "Use Backup e Dados para exportar o backup técnico em JSON antes de trocar de navegador ou computador e para restaurar a base quando necessário."],
  ["PDF de diagnóstico x PDF comercial", "O PDF de diagnóstico documenta o levantamento e a revisão das informações. O PDF comercial apresenta uma versão da solução recomendada. São documentos diferentes."],
  ["Capital segurado x prêmio x valor projetado x valor de resgate", "Capital segurado é a cobertura contratada. Prêmio é o valor pago pelo seguro. Valor projetado é uma estimativa futura quando formalmente aplicável. Valor de resgate é o valor disponível nas condições específicas do produto. Nenhum deles deve ser tratado como sinônimo de rendimento."],
  ["Metis, Assistente de Planejamento", "A Metis analisa diagnósticos, revisa propostas e prepara perguntas para a próxima reunião com dados minimizados. Use-a depois de registrar as informações estruturadas e revise profissionalmente cada sugestão."],
  ["O que a Metis não faz", "Ela não altera cadastro, diagnóstico ou proposta, não fecha proposta, não promete aceitação de seguro e não recomenda produto como decisão definitiva. A sugestão da IA é apoio. A decisão continua sendo da corretora."],
];

export default function HelpPage() {
  return <div className="page help-page"><section className="hero"><div><p className="eyebrow">GUIA OPERACIONAL</p><h2>Como conduzir um atendimento no 7Protect</h2><p>Siga as etapas na ordem para transformar uma oportunidade em relacionamento de carteira, preservando histórico e contexto.</p></div></section><section className="card help-intro"><p className="eyebrow">FLUXO COMPLETO</p><h3>Lead → Kanban → Cliente → Planejamento → Diagnóstico → Análise → Proposta → Apresentação → Fechamento → Carteira → Revisão</h3><p>O cadastro do cliente é permanente. O planejamento é uma fotografia daquele cliente em um contexto e uma data de referência.</p></section><section className="help-steps" aria-label="Etapas do guia operacional">{steps.map((step) => <article className="card help-step" key={step.number}><div className="help-step-number" aria-hidden="true">{step.number}</div><div className="help-step-content"><p className="eyebrow">ETAPA {step.number}</p><h3>{step.name}</h3><dl><div><dt>Objetivo</dt><dd>{step.objective}</dd></div><div><dt>Onde realizar</dt><dd>{step.where}</dd></div><div><dt>O que fazer</dt><dd>{step.action}</dd></div><div><dt>Concluída quando</dt><dd>{step.done}</dd></div><div><dt>Resultado esperado</dt><dd>{step.result}</dd></div></dl><Link href={step.href} className="button secondary">{step.button}</Link></div></article>)}</section><section className="card help-faq"><p className="eyebrow">FAQ E CONCEITOS IMPORTANTES</p><h3>Antes de avançar</h3><div className="faq-list">{faqs.map(([question, answer]) => <article key={question}><h4>{question}</h4><p>{answer}</p></article>)}</div></section></div>;
}
